### ISSUE TITLE
Integrating v0.14 with Symfony 6

### ISSUE THREAD

**Issue by ktrzos** [overblog/GraphQLBundle#1005]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.14

Is there any proper reason why v0.14 stable version still cannot be integrated with Symfony 6?

**Comment by mcg-web** [comment]
see [v0.15.0](https://github.com/overblog/GraphQLBundle/releases/tag/v0.15.0)
