### ISSUE TITLE
`ExecutorArgumentsEvent` root value type

### ISSUE THREAD

**Issue by ktrzos** [overblog/GraphQLBundle#1028]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | dev-master

In the `ExecutorArgumentsEvent` class the `$rootValue` constructor parameter has `mixed|null` type, but `getRootValue()` has `?array` type. Should it be like that? With it there's no way of setting up the root value as other than an array as it ends with an error when resolving it.

**Comment by mcg-web** [comment]
Thank you for the fix!
