### ISSUE TITLE
Symfony 2.7 requirement

### ISSUE THREAD

**Issue by keesschepers** [overblog/GraphQLBundle#105]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Version/Branch   | x.y.z

Hello,

We want to use this bundle but our project is still on Symfony 2.6. For which reason Symfony 2.7 is required?

**Comment by mcg-web** [comment]
Hi,

This is because support for Symfony 2.6 ended in January 2016. Never try to make it work with this version. If you can validate it work with it (without breaking tests), we can downgrade requirements to this version...
