### ISSUE TITLE
Publish new version?

### ISSUE THREAD

**Issue by Vincz** [overblog/GraphQLBundle#1057]
Hi @mcg-web !
Shouldn't we publish a new version with the latest updates?
It has been requested https://github.com/overblog/GraphQLBundle/discussions/1055
What do you think?

**Comment by mcg-web** [comment]
Hi @Vincz! 
Main branch release required that webonyx/graphql-php release v15. We can't release a stable version base on a non stable branch. Can try to push Webonyx to release but this is out of my scope.

**Comment by vladdnepr** [comment]
https://github.com/webonyx/graphql-php/discussions/1231

**Comment by cyrfli** [comment]
https://github.com/webonyx/graphql-php/releases/tag/v15.0.0 \o/ they did it! \o/

**Comment by vladdnepr** [comment]
@mcg-web so... new version?

**Comment by vladdnepr** [comment]
@mcg-web hi. When you release new version?

**Comment by vladdnepr** [comment]
https://github.com/overblog/GraphQLBundle/releases/tag/v0.15.0

**Comment by ettoredn** [comment]
`https://github.com/webonyx/graphql-php@^15` has fixed some deprecation related to PHP v8.2. Why doesn't the v0.15 require `webonyx/graphql-php@^15` and is still on the v14?

**Comment by TaProhm** [comment]
Hello @mcg-web. It would be awesome and quite useful to get a new version.

**Comment by ettoredn** [comment]
What's stopping you from releasing a new version?

**Comment by Vincz** [comment]
Hi guys. Sorry, I was waiting for https://github.com/overblog/GraphQLBundle/pull/1108.
I just need to check the version number with the boss and I'll publish the new version (today or tomorrow). 
Sorry again for the delay.

**Comment by vladdnepr** [comment]
> Hi guys. Sorry, I was waiting for #1108. I just need to check the version number with the boss and I'll publish the new version (today or tomorrow). Sorry again for the delay.

Sorry, but now I don't have free time for #1108 

Maybe we release this issue later in another release?

**Comment by Vincz** [comment]
The [v1.0](https://github.com/overblog/GraphQLBundle/releases/tag/v1.0.0) has been released !
