### ISSUE TITLE
Support resolveField

### ISSUE THREAD

**Issue by AndreasHeiberg** [overblog/GraphQLBundle#109]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.6.2

http://webonyx.github.io/graphql-php/data-fetching/#default-field-resolver-per-type

resolveField is a feature in webonyx that allows you to define a type level resolver. You can still put a resolver on individual fields if you like, but basically you get the opportunity to define the resolver at the type level as a default.

The problem is that you alway register the default resolver for any field that doesn't have a resolver regardless of there being a parent resolveField. This is honestly perfectly acceptable behaviour but it does break the resolveField use case because of https://github.com/webonyx/graphql-php/blob/master/src/Executor/Executor.php#L622-L628

There's some tradeoffs there that I don't wanna make on your behalf. Let me know if this makes sense.

**Comment by mcg-web** [comment]
Hi @AndreasHeiberg that's a known issue but we have "access" feature that rely on this. I'll try to see how we can implement **resolveField** easily without breaking this security feature... This should help decrease Closure instances indeed...

**Comment by AndreasHeiberg** [comment]
When do you think you might be able to work on this?

**Comment by mcg-web** [comment]
I'm working on this, it should be soon released.

**Comment by mcg-web** [comment]
This should fix the issue, feel free to reopen if needed. Thank you for reporting!
