### ISSUE TITLE
Lazy type loader

### ISSUE THREAD

**Issue by Roensby** [overblog/GraphQLBundle#1104]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.14

I have a huge number of types, fields and arguments. Storing these in a static file, be it yaml or GraphQL schema language, isn't really feasible.

Using webonyx/graphql-php I can load my types lazily, like so:

```
use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Schema;
use GraphQL\Type\SchemaConfig;

$schema = new Schema(
  SchemaConfig::create()
    ->setQuery($typeRegistry->getRootQuery())
    ->setTypeLoader(static fn (string $name): Type => $typeRegistry->getType($name))
));
```

Is there a way to do this in overblog/GraphQLBundle?

**Comment by Roensby** [comment]
This issue has been discussed previously: https://github.com/overblog/GraphQLBundle/issues/779
What has changed since then is that this bundle now supports version 14 of `webonyx/graphql-php`, presumably which allows for lazy loading.

**Comment by Roensby** [comment]
Answering my own question

This can be done by intercepting the call to the executor. I'm not sure if this is a good way to do it, but it does mean minimal changes when migrating from `webonyx/graphql-php` to `overblog/GraphQLBundle`.

```php

namespace App\EventListener;

use GraphQL\Type\Definition\Type;
use GraphQL\Type\SchemaConfig;
use Overblog\GraphQLBundle\Definition\Type\ExtensibleSchema;
use Overblog\GraphQLBundle\Event\ExecutorArgumentsEvent;

class ExecutorEventListener
{
    protected static SchemaConfig $schemaConfig;

    public function __construct(TypeRegistry $typeRegistry)
    {
        if (!isset(self::$schemaConfig)) {
            self::$schemaConfig = SchemaConfig::create()
                ->setQuery($typeRegistry->getRootQuery())
                ->setTypeLoader(static fn (string $name): Type => $typeRegistry->getType($name));
        }
    }

    public function onPreExecutor(ExecutorArgumentsEvent $event)
    {
        $event->setSchema(new ExtensibleSchema(self::$schemaConfig));
    }
}
```
From the documentation: https://github.com/overblog/GraphQLBundle/blob/master/docs/events/index.md#executor-initialisation

**Comment by andrii29** [comment]
hi,
@Roensby 
will lazy load be implemented in future release, or users should use your example to achieve lazy load?

**Comment by Roensby** [comment]
I don't know @andrii29, I'm not a maintainer of this repo, just a random user. It would be nice if there was better support for it.

**Comment by andrii29** [comment]
@murtukov @mcg-web,
can you comment these, please?
