### ISSUE TITLE
0.15.2 breaks with PHP8.2 and the latest version of webonyx/graphql-php

### ISSUE THREAD

**Issue by pascalwoerde** [overblog/GraphQLBundle#1106]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Version/Branch   | 0.15.2

The latest release 0.15.2 is published as fix, but it is a breaking change. Since it results in a downgrade of webonyx/graphql-php when 15 of later was already used. For PHP8.2 this will result in deprecation warnings and failing tests.

> <b>Deprecated</b>:  Using ${var} in strings is deprecated, use {$var} instead in <b>/var/www/html/vendor/webonyx/graphql-php/src/Validator/Rules/ValuesOfCorrectType.php</b> on line <b>182</b><br />

For now I use a fixed version 0.15.1 so that everything still works correctly. What is the reason that a downgrade is required, what does this fix?

`"overblog/graphql-bundle": "^0.15,!=0.15.2"`

**Comment by Vincz** [comment]
Fixed in latest master. We should publish a new proper version soon.

**Comment by aviator-ua** [comment]
@Vincz Is it possible to fix this issue in the 0.15 branch? 
From my side, it takes some time to update Symfony packages in my project to update to switch to latest 1.0

There is a small  PR for this https://github.com/overblog/GraphQLBundle/pull/1126
