### ISSUE TITLE
(Question) Is 1.0.0 a stable version?

### ISSUE THREAD

**Issue by esorinas** [overblog/GraphQLBundle#1135]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 1.0.0

I have seen that v1.0.0 has been published since July 7th, but in the documentation, it is marked as DEV

![image](https://github.com/overblog/GraphQLBundle/assets/43247096/61a136e7-aeb1-482f-8adc-5441ac5d1f67)

As of today, is this version stable?

Thank you very much!

**Comment by chou666** [comment]
Good question @esorinas, i try to migrate to version and i have issue (https://github.com/overblog/GraphQLBundle/issues/1129)

**Comment by mcg-web** [comment]
v1.0.0 is stable, documentation is not up to date sorry.
