### ISSUE TITLE
Symfony 7 support

### ISSUE THREAD

**Issue by sitepark-veltrup** [overblog/GraphQLBundle#1146]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 1.0

Is there already a plan when symfony 7 will be supported?

**Comment by Vincz** [comment]
Hi @sitepark-veltrup! Yes, Symfony 7 is planned. See here: https://github.com/overblog/GraphQLBundle/pull/1144 to follow.
