### ISSUE TITLE
MetadataParser will throw exception if you have Symfony PHP Configurations in your bundle

### ISSUE THREAD

**Issue by cfv1000** [overblog/GraphQLBundle#1152]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? |no
| RFC?             |no
| Version/Branch   | dev-master,1.0

I created the following boilerplate https://github.com/cfv1000/symfony-graphql/pull/1

Given a bundle with a PHP Configuration, the command  php bin/console graphql:validate will throw a MetadataParser exception at line 261

<img width="379" alt="image" src="https://github.com/overblog/GraphQLBundle/assets/3073353/80551498-7187-4a1e-98f2-7480c5db1bb2">

Under the following conditions
- Configure a bundle in symfony with working Overblog/GraphQL Bundle configuration
- create a .php configuration in the bundle

The library will break a feature supported by Symfony

**Comment by GrozescuRares** [comment]
I am also interested into this topic.

**Comment by Vincz** [comment]
Hi @cfv1000, I downloaded your projet and run it without error.  
Then I changed the `graphql.yaml` file into a `graphql.php` file like this: 
````php
<?php

namespace Symfony\Component\DependencyInjection\Loader\Configurator;

use function Symfony\Component\DependencyInjection\Loader\Configurator\param;

return static function (ContainerConfigurator $container): void {
    $container->extension('overblog_graphql', [
        // when using the param() function, you only have to pass the parameter name...
        'definitions' => [
            'schema' => [
                'query' => 'RootQuery'
            ],
            'mappings' => [
                'types' => [
                    ['type' => 'attribute', 'dir' => '%kernel.project_dir%/src/ApplicationBundle', 'suffix' => null]
                ]
            ]
        ]
    ]);
};
````

and run it again, and didn't get any error.  
Do you mind to update your project with the configuration that leads to the error?

**Comment by cfv1000** [comment]
@Vincz  - there is an open pull request - if you change the branch from main to that pull request branch, and run the command again you should get the same error as i had

**Comment by Vincz** [comment]
Ok, I understand. When we use a mapping with attributes, we expect the configured directories to contain only PHP files containing classes.  
That's why you get this error.  
One solution is to exclude this directories from the mapping parsing or be more specific on the directories containing your mapping.  
We could also check if the class does exist before trying to parse it in the `MetadataParser`. Feel free to submit a PR if you want, otherwise, I'll add this later.
