### ISSUE TITLE
Usage with DataLoader: How to return a warning if one ID wasn't found

### ISSUE THREAD

**Issue by adri** [overblog/GraphQLBundle#121]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | master

First of all, thanks so much for the work on all these bundles. Works really well! 👍 

I'm using `overblog/graphql-bundle` and `overblog/dataloader-bundle` on `master` with the configuration [described in this ticket](https://github.com/overblog/GraphQLBundle/pull/73#issuecomment-285598005). 
When implementing the `load` method in the data loader I'm returning a list of objects in the order of the `keys`. Sometimes it can happen that a `key` is requested for a non-existing object. 
I'm using the following helper:

```php
    public static function orderObjectsById(array $ids, array $unorderedObjects, string $idField = 'id') : array
    {
        $idToIndexMap = array_flip(array_column($unorderedObjects, $idField));
        $objects = [];

        foreach ($ids as $id) {
            if (false === isset($idToIndexMap[$id])) {
                $objects[] = new UserWarning("Object with id '$id' not found");
            } else {
                $objects[] = $unorderedObjects[$idToIndexMap[$id]];
            }
        }

        return $objects;
    }
```

I thought I'll place a `UserWarning` for the object that is missing. When debugging I saw that this results in the promise for only this object being rejected which is perfect. 

For some reason the `data` that is passed to the `Executor::executeQuery` promise is `null`. I would expect that it shows all data that is available, except the missing object. 

Response: 
```json
{
  "data": [],
  "extensions": {
    "warnings": [
      {
        "message": "Not found",
        "locations": [
          {
            "line": 100,
            "column": 3
          }
        ],
        "path": [
          "test"
        ]
      }
    ]
  }
}
```

How could I debug this further? I'm having troubles to find how the `$data` gets to [this part of the code](https://github.com/webonyx/graphql-php/blob/master/src/Executor/Executor.php#L240).

Thanks a lot!

**Comment by mcg-web** [comment]
hi @adri, 

DataLoader doesn't take a not existing key as an error, the only solution is to chain your promise and throw exception if result is null.

with something like this:

```php
    public function resolveShip($shipID)
    {
        $promise = $this->container->get('ships_loader')->load($shipID);

        return $promise->then(function ($result) use ($shipID) { 
             if (null === $result) {
                   throw new UserWarning("Object with id '$shipID' not found");
             }
        });
    }
```

you must return null for not existing result for this to work...

**Comment by adri** [comment]
Awesome, thanks for your quick help!
