### ISSUE TITLE
Deprecation warnings on Symfony 3.2.*

### ISSUE THREAD

**Issue by madarco** [overblog/GraphQLBundle#136]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.8.0

Hi,
we get a few deprecation warning on for the use of `ArrayParserCache` on Symfony 3. 
They were easy to fix: https://github.com/overblog/GraphQLBundle/compare/master...madarco:master

However, I don't know if those break BC with Symfony 2.

Hope this could help others with the same issue.

Marco D'Alia

**Comment by mcg-web** [comment]
Hi @madarco,

Thank you for the feedback. This is a BC but we can integrate it to the 0.9 dev version (branch 0.9). you must also add the requirement `"symfony/cache": "^3.1"` to composer to be compatible with symfony 2.8 (we abandoned sf 2.7 and php 5.4 in this version).

**Comment by mcg-web** [comment]
fixed in v0.8.1
