### ISSUE TITLE
SY webprofiler broken in graphiql

### ISSUE THREAD

**Issue by akomm** [overblog/GraphQLBundle#139]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.8.0

Wen I open the graphiql provided by this bundle, I have the following issues:

- The WP toolbar is open on page load
- The WP toolbar can not be closed. It covers variables input in graphiql.
- The toolbar-info positions (mouseover detail-toolstips) are not correctly aligned. The right most is therefore out of client width boundaries.
- *added* XHR request info is updated for a moment and then cleared. 

Researching I found the reason. 

The `graphQLFetcher` updates the toolbar DOM [here](https://github.com/overblog/GraphQLBundle/blob/2b6c40a/Resources/views/GraphiQL/index.html.twig#L51) (GraphQLBundle)

The WP toolbar inject an initializer script [here](https://github.com/symfony/symfony/blob/6327b4161d2bf6fa71a50855fb90a51c0a6fe655/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/toolbar_js.html.twig) (WebProfilerBundle)

The initialization includes:
- [Positioning toolbar-info](https://github.com/symfony/symfony/blob/6327b4161d2bf6fa71a50855fb90a51c0a6fe655/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/toolbar_js.html.twig#L47-L68)
- [Registering click handlers queriend DOM by id including initial token](https://github.com/symfony/symfony/blob/6327b4161d2bf6fa71a50855fb90a51c0a6fe655/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/toolbar_js.html.twig#L70-L94)

Problem:
- [Issue cause] When the toolbar DOM is replaced in `graphQLFetcher` the events are not attached on the new DOM
- [Additional] Old events are not unregistered.

**Comment by mcg-web** [comment]
Thanks for bringing up this bug.

**Comment by akomm** [comment]
Since the XHR info is broken anyway, removing the .load call in `graphQLFetcher` actually improves the situation. At least you can close the toolbar and you can see the XHR request history this way. 

There is sadly no API from Sfjs side to reload it (or I missed it somewhere) and the initializer is in an IIFE. One possible way to fix it I see is store the template in a JS variable as string with token and evtl. nounce placeholder to replace and inject new script tags with the IIEF string content...

**Comment by mcg-web** [comment]
The best solution is to remove the reload, i think right now.

**Comment by mcg-web** [comment]
Removed in 0.8.2. I also added a twig block to leave possibility to implement this in overridden template. Thanks again for reporting.
