### ISSUE TITLE
[Feat] Melt type/build+definition concepts

### ISSUE THREAD

**Issue by akomm** [overblog/GraphQLBundle#141]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | ^0.7

I came to an idea, when I was searching for answers. I wanted to know how you modified types like `relay-mutation-payload` without the requirement to provide `build` & `builderConfig`. I found the [definition file](https://github.com/overblog/GraphQLBundle/blob/89ec616892e9e15ab3c19aed130d90e648b43faf/Relay/Mutation/InputDefinition.php), but the only way I knew to use it, is to define a `builder` & `builderConfig`. Then I found [this](https://github.com/overblog/GraphQLBundle/blob/89ec616892e9e15ab3c19aed130d90e648b43faf/DependencyInjection/TypesConfiguration.php#L122-L184).

You basically pass some parts of the fields configuration to a given builder as its config.
It looks hard-coded to me - I could not find a way to do it myself just via extension configuration.

Then came the idea:

Why not melt the builder concept and what you do in `\Overblog\GraphQLBundle\DependencyInjection\TypesConfiguration` into a single concept?

Basically: field Type = builder alias. 

Maybe even drop the naming `builder` and just keep the `definition` which would make more sense with the unification. 

Additionally I'v noticed that you can also map args in field builder. So far I did not find any use case for the args builder. Is there any reason for it to exist at all? The less concepts to achieve the same results, the easier to [grok](https://en.wikipedia.org/wiki/Grok) ! :)

Advantages could be:
- Less configuration/configuration nesting (builder, builderConfig)
- No hard-coded type normalization like `relay-mutation-payload` required anymore
- Users can define types the same way as default bundle types like `relay-mutation-payload` are currently defined.
- Less naming confusion (definition/builder) in my opinion (easier to [grok](https://en.wikipedia.org/wiki/Grok) )

**Comment by mcg-web** [comment]
Not really knows where this could bring us but it deserve we give it a try. Any way thanks for your ideas, this helps improved the bundle...

**Comment by akomm** [comment]
This might be a larger change and BC break I think. I'm also not entirely sure whether this has some disadvantages, due to the fact that I do not use the bundle very long now, so still grok-ing through it. But after testing some alternatives this bundles approach in my opinion is the best one so far :)

**Comment by mcg-web** [comment]
closing this in favor of #290
