### ISSUE TITLE
[Bug] builder changes do not invalidate cache

### ISSUE THREAD

**Issue by akomm** [overblog/GraphQLBundle#142]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.8.0

Builders are only used at compile time. This is good. But because they are not configuration resources (only their "declaration" in config) changes in the implementation code do not invalidate the cache. 

Is it possible to add the builder files as config resources too, so their changes invalidate cache?

**Comment by mcg-web** [comment]
Yes this should be the case in fact... Thanks for bringing this up :+1: !

**Comment by mcg-web** [comment]
v0.8.3 should fix this, feel free to reopen if this is not the case.
