### ISSUE TITLE
JSON Schema incompatible with Relay Compiler

### ISSUE THREAD

**Issue by ste93cry** [overblog/GraphQLBundle#150]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | yes
| RFC?             | no
| Version/Branch   | master

Although I could not find a official specification on the topic, the official `babel-plugin-relay` plugin from Facebook (Relay Modern) expects the JSON schema to be enclosed in a `data` object. This is what is generated from the `graphql:dump-schema`:

```json
{
    "__schema": {}
}
```

And this is what the plugin expects:

```json
{
    "data": {
        "__schema": {}
    }
}
```

The problem relies at [GraphQLDumpSchemaCommand#82](https://github.com/overblog/GraphQLBundle/blob/f038ea2f230a3c5c782899806204883c51a3067a/Command/GraphQLDumpSchemaCommand.php#L82) where the `json_encode` function is applied on the `data` element instead of the `$result` variable itself. Changing this would indeed be a BC break, but at the moment the JSON schema is unusable with the Relay Modern compiler

**Comment by ooflorent** [comment]
We will add a flag `--compat` to preserve the current output (compatibility with Relay classic) and change how the command works.

**Comment by ooflorent** [comment]
**Note:** This is a breaking change that has to be made.

**Comment by ste93cry** [comment]
If the flag was for the new output (something like `--modern` instead of `--compat`) then there would be no BC break

**Comment by ooflorent** [comment]
After discussions with @mcg-web we decided to add two flags: `--modern` and `--classic` and a config parameter to specify the default behavior.

**Comment by mcg-web** [comment]
Merged on master. No release right now. See PR for more information
