### ISSUE TITLE
Is there any way to throw multiple InvariantViolation exceptions as UserErrors?

### ISSUE THREAD

**Issue by ssimplix** [overblog/GraphQLBundle#158]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.8.4

Hi. I'm building validation for arguments, but it seems there is no way to throw an array of exceptions like `UserErrors`:

````php
namespace AppBundle\GraphQL\Resolver;

use AppBundle\Entity\User;
use AppBundle\Form\RegistrationForm;
use GraphQL\Error\InvariantViolation;
use Overblog\GraphQLBundle\Definition\Argument;
use Overblog\GraphQLBundle\Error\UserErrors;
use Symfony\Component\Form\FormErrorIterator;
use Symfony\Component\Security\Core\User\UserInterface;

class UserResolver extends AbstractBaseResolver
{
    public function register(Argument $args): User
    {
        $rawArgs = $args->getRawArguments();

        $form = $this->createForm(RegistrationForm::class, $rawArgs);

        $form->submit($rawArgs);

        if ($form->isValid()) {
            return $this->get('app.service.user')->register($form);
        }

        $errors = [];

        /** @var FormErrorIterator $error */
        foreach ($form->getErrors(true, false) as $error) {
            $errors[] = new InvariantViolation(sprintf(
                '%s: %s',
                $error->current()->getOrigin()->getName(),
                $error->current()->getMessage()
            ));
        }

        throw new UserErrors($errors);
    }
}
````

If I throw simple `InvariantViolation` exception like this, I get only one error:

````php
    public function register(Argument $args): User
    {
        $rawArgs = $args->getRawArguments();

        $form = $this->createForm(RegistrationForm::class, $rawArgs);

        $form->submit($rawArgs);

        if ($form->isValid()) {
            return $this->get('app.service.user')->register($form);
        }

        $errors = [];

        /** @var FormErrorIterator $error */
        foreach ($form->getErrors(true, false) as $error) {
            throw new InvariantViolation(sprintf(
                '%s: %s',
                $error->current()->getOrigin()->getName(),
                $error->current()->getMessage()
            ));
        }
    }
````

**What should I do to get error response for this mutation**:

````graphql
mutation {
  register(
    firstName: "foo@asdas.rфe"
    email: "foo@baвпr.ru"
    lastName: "bar"
    middleName: "baz"
    password: "1235678"
    phone: "sdaфывввsd"
    sex: MALE
  ) {
    email
  }
}
````

Like this one:

````json
{
  "data": {
    "register": null
  },
  "errors": [
    {
      "message": "phone: Это значение уже используется.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": ["register"]
    },
    {
      "message": "password: Значение слишком короткое. Должно быть равно 8 символам или больше.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": ["register"]
    }
  ],
  "extensions": {
    "debug": {
      "executionTime": "72 ms",
      "memoryUsage": "0.00 MiB"
    }
  }
}
````

Also is there any way to add extra fields to the error?

Thanks.

**Comment by mcg-web** [comment]
>Hi. I'm building validation for arguments, but it seems there is no way to throw an array of exceptions like UserErrors

Hi after searching `InvariantViolation` should not be use (in custom scalar or in resolver) and it'll be soon consider like a system error by the bundle ([see the issue here](https://github.com/webonyx/graphql-php/issues/123)). So you should consider using `UserError` or/and `UserErrors...

>Also is there any way to add extra fields to the error?

Unfortunately each resolver is attach to a particular field (path) so throwing exception will affects only this field.

**Comment by ssimplix** [comment]
> Unfortunately each resolver is attach to a particular field (path) so throwing exception will affects only this field.

@mcg-web, thank you for your reply. I want to add field "argument" to tell client which field isn't valid. How client should map these errors with form fields? How client should recognize that this error is form validation error?

Something like this:

````json
{
  "data": {
    "register": null
  },
  "errors": [
    {
      "message": "This phone already registered in the system.",
      "code": 100,
      "argument": "phone",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    },
    {
      "message": "Password is too short.",
      "code": 100,
      "argument": "password",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
````

Where error code `100` means argument validation error. Can you provide an example please how to do this using `UserError`?

**Comment by mcg-web** [comment]
This is not possible error most respect the [GraphQL specs](https://facebook.github.io/graphql/#sec-Errors). A solution is to format the message adding useful information like the error code (json format ?). 

```json
{
  "data": {
    "register": null
  },
  "errors": [
    {
      "message": "{ \"message\": \"Password is too short.\", \"code\": 100, \"argument\": \"password\"}",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
```
**Note** this is just a example not the cleaner way but respects the specs.

**Comment by ssimplix** [comment]
@mcg-web, having extra fields is actually addressed in the spec as well:

> GraphQL servers may provide additional entries to error as they choose to produce more helpful or machine‐readable errors, however future versions of the spec may describe additional entries to errors

**Comment by mcg-web** [comment]
ok this is a new feature that not supported right now by the bundle and by the main lib `webonyx/graphql-php`.

**Comment by mcg-web** [comment]
closing this in favor of #182
