### ISSUE TITLE
[feat] overwrite or disable default builders (alias)

### ISSUE THREAD

**Issue by akomm** [overblog/GraphQLBundle#159]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | master

I just noticed, that default builders like 'Mutation' do not get replaced when you define own with the same alias. Naming it different would break my convention. 

I like this bundle, it gives a good base to work with. Just the default builders do not fully match my requirements and I decided to make my own set combined with some generic flow. Reusing and extending around the existing builders would overcomplicate what I need.

Would be nice if one could replace the default one or at least disable (flag yes/no for all) if the overwriting is a problem in compiler pass.

**Comment by mcg-web** [comment]
This is not the wanted behavior so this is a bug, can you provide a fast example that reproduce this please?

**Comment by akomm** [comment]
Sorry. It was a cache issue which confused me when I tried to track back the reason for an error. Works as you said.
