### ISSUE TITLE
Support query batching for Apollo GraphQL

### ISSUE THREAD

**Issue by rpander93** [overblog/GraphQLBundle#163]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | all

Hi,

We're currently developing an app using this bundle in our Symfony code to create a GraphQL endpoint. In the front-end, we use Apollo (apollodata.com) to send queries. We tried to make batching work, but no luck so far. The docs of Apollo describe their method of [here](http://dev.apollodata.com/core/network.html#query-batching). I compared this to the docs of the linked ReactRelayNetworkLayer to compare the methods of handling batched requests. It seems ReactRelayNetworkLayer uses "id" to identify between queries while Apollo uses "operationName". So I tried changing the [controller 
](https://github.com/overblog/GraphQLBundle/blob/master/Controller/GraphController.php#L74) but this didn't fix the issue unfortunately.

Any developers faced a similar issue that were able to fix it?

**Comment by mcg-web** [comment]
Hi,

I think the big difference cames from the response payload not the request it self, [here the way ReactRelayNetworkLayer Batching works](https://github.com/nodkz/react-relay-network-layer#how-batching-works-internally) and [here Apollon batching](https://dev-blog.apollodata.com/query-batching-in-apollo-63acfd859862) look to be more straight forward. We can implement a way of switching between both...

**Comment by rpander93** [comment]
Hi, thanks for the reply. I also found the blogpost you linked to but that method of batching does not seem to work anymore. If you look at the source of [Apollo Client](https://github.com/apollographql/apollo-client/blob/master/src/ApolloClient.ts#L122) is visible that the mentioned "shouldBatch" option is not there anymore. The blogpost also dates from June 2016. I will do some more testing this and next week to hopefully pinpoint the problem.

**Comment by omarsoufiane** [comment]
same here,  we are also developping a symfony app with apollo in the client,  i haven't tested batching, but i think it would be a a great idea to make this bundle support apollo too, 
@rpander93 i'm also working on a subscription bundle on top of this bundle to support realtime updates on an apollo client, i'll share it with you when it will be working
