### ISSUE TITLE
Question: Error handler for sending critical errors

### ISSUE THREAD

**Issue by adri** [overblog/GraphQLBundle#164]
Just a question;
I'd like to send critical errors to a log collection service like [sentry](https://sentry.io). What would be a good way to do this? I checked the docs but couldn't find information about this.

For now I extend the `Overblog\GraphQLBundle\Error\ErrorHandler` and inject an error handler instance next to a sentry client instance to log critical errors to sentry. But it feels a bit strange to extend and inject the error handler. Maybe a `ErrorHandler` interface would be the way to go? Any advice? 

Thanks a lot for an awesome bundle!

**Comment by mcg-web** [comment]
Hi,

An interface is a way to go but could add some complexity in some cases, we could add an event with the dispatcher after getting the ExecutionResult. Right now there is no "clean" way of doing this unfortunately...

**Comment by adri** [comment]
Hey :) Thanks a lot for your quick answer. 
Thanks a lot. I'll think about it and maybe come up with a PR.
