### ISSUE TITLE
Broken code when using dedicated CI server

### ISSUE THREAD

**Issue by edefimov** [overblog/GraphQLBundle#167]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.8.5

When the bundle compiles GraphQL type classes, the absolute path to generated class is stored under the cache directory inside the ___classes.map_ file. However if application is built on dedicated CI server, the stored absolute path is pointing to temporary build directory. This makes an application broken right after deployment to target environment since the absolute path to generated classes has changed.

**Comment by mcg-web** [comment]
Hi, this issues can be fix by replacing absolute hard coding path by the **__DIR__** constant... I'll submit a PR today to fix this.

**Comment by mcg-web** [comment]
Released in v0.8.6, feel free to re-open if needed.

**Comment by edefimov** [comment]
It works, thanks!
