### ISSUE TITLE
How to have mutiple query.types.yml files ?

### ISSUE THREAD

**Issue by blade503** [overblog/GraphQLBundle#169]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

I Would like to know how can we declare several Query.types.yml ? i think it might be in the config But when i take a look at the documentation i don't succeed to understand how I should declare them. 

I have two bundle, and i would like to declare on file query.types.yml by bundle. Cause one bundle is for car and the other is for User. How can i do this ? 

I though maybe give an array of query files in the config.yml would work, but no...

**Comment by mcg-web** [comment]
hi,

Type name should be unique but if you need multiple schema you can [use this](https://github.com/overblog/GraphQLBundle/blob/master/Resources/doc/definitions/schema.md#multiple-schema-endpoint)...

**Comment by blade503** [comment]
that's not really what i would like. I would like one main schema that i can subdivise in order to put the query in differents bundle. Like this if i want a query about car i only have to go in my car Bundle and they will be there. 

Or can i For example create a carQuery.types.yml and userQuery.type.yml and import them in Query.Types.yml ?

**Comment by mcg-web** [comment]
This is not possible right now. The only way is to add an unique Query.types.yml in one of two bundle and reference types from you second bundle... We should add a option to enabled types config overriding/merging (this is disabled by default)

**Comment by blade503** [comment]
Ok thanks in this case i will try to do it with one file only
