### ISSUE TITLE
Rename graphqls into graphql

### ISSUE THREAD

**Issue by ooflorent** [overblog/GraphQLBundle#170]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | master

We should rename the `format` command option value `graphqls` into `graphql`.
Moreover, we should also rename the default schema name into `schema.graphql`.

**Comment by mcg-web** [comment]
done! will be release later...
