### ISSUE TITLE
webonyx/graphql-php to v0.10?

### ISSUE THREAD

**Issue by calvera** [overblog/GraphQLBundle#177]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | x.y.z

hi! any plans updating webonyx/graphql-php to v0.10? thanks

**Comment by mcg-web** [comment]
hi! this upgrade will be soon release in 0.9.0 version...

**Comment by calvera** [comment]
@mcg-web: :+1:

**Comment by mcg-web** [comment]
released in [v0.9 pre-version](https://github.com/overblog/GraphQLBundle/releases/tag/v0.9.0-BETA1). Feel free to reopen if needed
