### ISSUE TITLE
Support resolving of Doctrine collections in the default resolver

### ISSUE THREAD

**Issue by ste93cry** [overblog/GraphQLBundle#180]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | yes, possible
| RFC?             | no
| Version/Branch   | master

Trying to resolve a variable that is a [Doctrine collection](https://github.com/doctrine/collections) to a Relay connection with the default resolver throws an error because it considers it an object and tries to get the value from a property with the name of the field which obviously does not exists. Does it makes sense to support collections out-of-the-box? In my project to fix this I'm using the following piece of code:

```php
$paginator = new Paginator(function (int $offset, int $limit) use ($collection) {
    return $collection->slice($offset, $limit);
});

return $paginator->auto($args, $collection->count());
```

If the collection is a relation of a Doctrine entity marked as `EXTRA_LAZY` the `count()` and `slice()` functions will be optimized to not load the entire dataset

**Comment by mcg-web** [comment]
Hi @ste93cry,
right now we do not want to support any specific ORM out-of-the-box that's why we trying to stay the more generic as possible. You can add your snippet to documentation if you wish, this can be helpful for doctrine users. 
Thanks anyway for sharing that with us :+1:

**Comment by akomm** [comment]
GraphQL is amazing because it does not care about data source. It just want & ensure you provide, what you promised.

**Comment by mcg-web** [comment]
closing this right now, feel free to reopen if needed
