### ISSUE TITLE
Set Error Formatter?

### ISSUE THREAD

**Issue by calvera** [overblog/GraphQLBundle#182]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Version/Branch   | 0.10

hi, i would appreciate to use my own error formatter in https://github.com/overblog/GraphQLBundle/blob/0b3b90ec54f06c7cc686962b3528fc0aae0b2e5e/Error/ErrorHandler.php#L160 . I'm able to prepare PR, are you interested?

**Comment by mcg-web** [comment]
Hi, yes I'm interested @calvera :+1:

**Comment by mcg-web** [comment]
Need some helps on this @calvera ?

**Comment by calvera** [comment]
i have this https://github.com/calvera/GraphQLBundle/commit/ba78ee85ce6b10b9e18d1c7bfb7822fe3f390ceb but i did not have time for polishing the code and write docs ...

**Comment by mcg-web** [comment]
Integrated to master will be released in 0.11, you can see [how to use here](https://github.com/overblog/GraphQLBundle/blob/master/Resources/doc/error-handling/index.md)
