### ISSUE TITLE
Support schema types lazy loading

### ISSUE THREAD

**Issue by adri** [overblog/GraphQLBundle#184]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.9

[Webonyx/graphql-php 0.10](https://github.com/webonyx/graphql-php/releases/tag/v0.10.0) added [lazy loading of schema types](https://github.com/webonyx/graphql-php/blob/df1b575469cb005b17088f0dcdf4d4543f7abac4/docs/type-system/schema.md#lazy-loading-of-types). As far as I can see currently [all types are passed to the schema](https://github.com/overblog/GraphQLBundle/blob/master/Definition/Builder/SchemaBuilder.php#L50).

I was wondering if there are plans already to support this? If not I could give it a go.

**Comment by mcg-web** [comment]
Hi @adri, it easy to put this in place. The TypeResolver is just like a typeLoader...

**Comment by adri** [comment]
Cool thanks. When I look at the `TypeResolver` it seems like it has all types already added using `addSolution`. Do you have a hint where this is called and how this could be made lazy?

**Comment by mcg-web** [comment]
`addResolver`can accept mixed type so we can add type like a closure(to be made lazy loading)! I'm working on this...

**Comment by adri** [comment]
Ow nice thanks!

**Comment by mcg-web** [comment]
Released in [v0.9.0-BETA2](https://github.com/overblog/GraphQLBundle/releases/tag/v0.9.0-BETA2)... Closing this right now, feel free to reopen if needed.

**Comment by adri** [comment]
You’re awesome, thanks a lot!
