### ISSUE TITLE
The webonyx/graphql-php requirement does not allow the latest release

### ISSUE THREAD

**Issue by stof** [overblog/GraphQLBundle#193]
the requirement for `webonyx/graphql-php` is currently `^0.10.1`, which translates to `>= 0.10.1, <0.11.0` (i.e. any version higher than `0.10.1`, until the next BC-breaking version).
This excludes the 0.11.0 release of the library.

**Comment by mcg-web** [comment]
Yes that was a choice we made at start of the bundle. `webonyx/graphql-php` was at it start too, major versions was often released and to keep this project stable as possible we decided to do so. This lock could maybe be remove right now... I don't really know what the best practice when being depend of a lib in open source. Thanks again for your feedback

**Comment by stof** [comment]
Well, I'm all in favor of using the semver operator (forbidding to upgrade to the next major versions makes sense, until you have tested it).

But you should then consider testing your bundle with 0.11 now, and change your requirement to allow it (either `^0.10.1 || ^0.11` or just `^0.11`).

I opened this issue because I was not sure that this was a choice you made, or just a misunderstand of how semver works before 1.0 (I saw such misunderstandings many times). 
And I saw that the latest version of the libwas not in the constraint range when reviewing the flex recipe of the bundle.

**Comment by renatomefi** [comment]
Seems like https://github.com/overblog/GraphQLPhpGenerator/blob/master/composer.json has to be updated before, since it's locked on 0.10.*

**Comment by mcg-web** [comment]
yes @renatomefi i'm going to be lease restrictive in the future... thank you to both of you for your feedback...

**Comment by renatomefi** [comment]
@mcg-web I think this can be closed since both libraries are now accepting 0.10 and 0.11 right?

**Comment by mcg-web** [comment]
yes this can be close, thank you to everyone :+1:
