### ISSUE TITLE
Autowiring deprecation warning

### ISSUE THREAD

**Issue by jradtilbrook** [overblog/GraphQLBundle#204]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Version/Branch   | 0.9

This is just to let you know I have installed this bundle in a new app and am getting a deprecation warning: `Autowiring-types are deprecated since Symfony 3.3 and will be removed in 4.0. Use aliases instead.`  
I am very new to Symfony (first app) so I'm not fully sure how to fix this yet, but thought I'd let you know if you don't already. If/when I get up to speed, if this hasn't been resolved I'll look into a PR for you.
Thanks!

**Comment by mcg-web** [comment]
the fix will be release in `0.9.1`

**Comment by mcg-web** [comment]
0.9.1 was released, feel free to reopen if needed :+1:
