### ISSUE TITLE
Drop library sllh/php-cs-fixer-styleci-bridge

### ISSUE THREAD

**Issue by renatomefi** [overblog/GraphQLBundle#206]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Version/Branch   | 0.10.0

- The library isn't updated for months already https://github.com/Soullivaneuh/php-cs-fixer-styleci-bridge
- Updating php-cs-fixer to 2.0 is now impossible simple the custom rules aren't ported
```
Fixer "ordered_use" does not exist, skipping.
Fixer "short_array_syntax" does not exist, skipping.
Fixer "unalign_equals" does not exist, skipping.
Fixer "blank_line_before_break" does not exist, skipping.
Fixer "blank_line_before_continue" does not exist, skipping.
Fixer "blank_line_before_declare" does not exist, skipping.
Fixer "blank_line_before_throw" does not exist, skipping.
Fixer "blank_line_before_try" does not exist, skipping.
Fixer "concat_without_spaces" does not exist, skipping.
Fixer "method_visibility_required" does not exist, skipping.
Fixer "no_blank_lines_after_throw" does not exist, skipping.
Fixer "no_blank_lines_between_imports" does not exist, skipping.
Fixer "no_extra_block_blank_lines" does not exist, skipping.
Fixer "no_spaces_inside_offset" does not exist, skipping.
Fixer "no_spaces_outside_offset" does not exist, skipping.
Fixer "no_tab_indentation" does not exist, skipping.
Fixer "phpdoc_link_to_see" does not exist, skipping.
Fixer "phpdoc_type_to_var" does not exist, skipping.
Fixer "print_to_echo" does not exist, skipping.
Fixer "property_visibility_required" does not exist, skipping.
Fixer "single_line_class_definition" does not exist, skipping.
Fixer "unalign_double_arrow" does not exist, skipping.
Fixer "unix_line_endings" does not exist, skipping.
```
- The current tag 2.7 doesn't even support php-cs-fxer 2.0 and fails while trying to call Config::finder()
- Maintainers aren't looking forward to make the necessary updates: 
 https://github.com/Soullivaneuh/php-cs-fixer-styleci-bridge/issues/76

I wonder what's the real advantage to use it, could you elaborate?
The really only one I see right now is the support for the header comment in the php files

**Comment by mcg-web** [comment]
Hi @renatomefi the choice of using this was made to ease contribution without loosing copyright...

**Comment by renatomefi** [comment]
@mcg-web is it because of the file header?

**Comment by renatomefi** [comment]
Let me know if you would consider dropping it, I have a WIP PR with a proposal, if not we can keep it but forever (possibly) stuck with php-cs-fixer 1.*

**Comment by mcg-web** [comment]
It is  also useful for basic coding standard, but all new solution is welcome

**Comment by renatomefi** [comment]
@mcg-web I was able to find a replacement to the headers feature, please check the PR, I think this library isn't adding much anymore!

**Comment by mcg-web** [comment]
after discussing  with @ooflorent, dropping licence header is not a bad think, the project license is already accessible in LICENCE file so no need to duplicate it...

**Comment by renatomefi** [comment]
@mcg-web I already fixed the header issue, but if you want I can drop all the headers in my current PR. So what's the decision? :)

**Comment by mcg-web** [comment]
Dropping it, removed a useless dependency
