### ISSUE TITLE
Contributors communication

### ISSUE THREAD

**Issue by renatomefi** [overblog/GraphQLBundle#221]
Hello,

With the raise of contributors would be good to have a more direct communication line.
Could we open a slack or something like that?

**Comment by renatomefi** [comment]
Actually my idea would be to create a channel on the symfony devs slack, would be more centralized and easier for more people to join

**Comment by mcg-web** [comment]
@renatomefi  this is a good idea. I'm creating the channel :+1:

**Comment by mcg-web** [comment]
#overblog-graphql

**Comment by renatomefi** [comment]
Cool! To close this let's just update the readme file :)
