### ISSUE TITLE
Explicit generation of Types

### ISSUE THREAD

**Issue by hgraca** [overblog/GraphQLBundle#228]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.9.0

We don't want to generate Types classes all the time, so we want to restrict Types generation to an explicit CLI command. For that we need:

1. A flag in the configuration to turn off the automatic generation of the Type Classes;
2. A CLI command to generate those classes from the configuration.

**Comment by mcg-web** [comment]
Feature will be release in next major version, but feel free to test and feedback if needed...

**Comment by hgraca** [comment]
Tkx a lot for this man!
