### ISSUE TITLE
Can I use schema.graphql file to define my schema?

### ISSUE THREAD

**Issue by enumag** [overblog/GraphQLBundle#248]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.9

Is it possible to use schema.graphql file as described in webonyx/graphql-php [docs](http://webonyx.github.io/graphql-php/type-system/type-language/#defining-your-schema)?

If it is already possible with this bundle I apologize but I was unable to find it in the documentation.

Also do you think it's a good practice to use such files instead of PHP classes? I like it as it is more compact and I can just take the file and send it to frontend developer.

**Comment by mcg-web** [comment]
Using schema.graphql is not possible right now , this is a coming feature... But you can dump your schema in graphql schema language format using the command `bin/console graphql:dump-schema --format=graphql --file=schema.graphql` this file can easily be share the frontend...

**Comment by enumag** [comment]
Is there an existing issue I should subscribe to?

**Comment by mcg-web** [comment]
Here the https://github.com/overblog/GraphQLBundle/issues/12 but fee free to add feedbacks

**Comment by enumag** [comment]
Thank you!
