### ISSUE TITLE
Missing error handling examples

### ISSUE THREAD

**Issue by enumag** [overblog/GraphQLBundle#256]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | master

I only found [this page](https://github.com/overblog/GraphQLBundle/blob/master/Resources/doc/security/errors-handling.md) but the way described there is not very useful.

I send a mutation to the server:

```
mutation {
  doSomething(
    id: "some invalid value",
    name: "",
  )
}
```

Using the described method I have a response like this:

```
{
  "errors": [
    {
      "message": "This is not a valid UUID.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    },
    {
      "message": "This value should not be blank.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ],
  "data": []
}
```

Which is of course completely unhelpful.

Firstly it's not clear at all which error belongs to which field - and I need that as a separate property in the json,not just add it to the error message.

Secondly the locations things are quite useless since they will be the same for all errors anyway.

I need to return something like this:

```
{
  "errors": [
    {
      "path": "id",
      "message": "This is not a valid UUID.",
      "code": "bb1cd37f-dd34-429e-a455-38e96e6b2bca"
    },
    {
      "path": "name",
      "message": "This value should not be blank.",
      "code": "7c5f1843-86b2-4ef1-8cb6-9b6a401e3ae5"
    }
  ],
  "data": []
}
```

If the location needs to be there, well whatever. But I need a way to add the custom fields alongside the message.

**Comment by enumag** [comment]
Even better would be to return an even better structure as described in [this article](https://medium.com/@tarkus/validation-and-user-errors-in-graphql-mutations-39ca79cd00bf).

**Comment by mcg-web** [comment]
I think the bundle will never cover all user needs on this subject (as errors section can accept extra fields #158)... The easier solution is maybe to give a way to override error handler and formatter just like in the webonyx lib. Anyway if you have an other idea feel free to share or contribute :+1: .

**Comment by enumag** [comment]
For now I'll try to completely disable error handling by this library and override webonyx's behavior.

By the way why does this library implements error handling instead of using webonyx's? Is there some problem with using that?

**Comment by mcg-web** [comment]
It is just legacy, the bundle introduce error handler before webonyx lib...

**Comment by enumag** [comment]
Then using webonix's is probably the best approach anyway. I'll share what I come up with. Thank you!

**Comment by mcg-web** [comment]
closing this in favor of #182
