### ISSUE TITLE
  Notice: Undefined index: relay-connection  

### ISSUE THREAD

**Issue by bitcoinporn** [overblog/GraphQLBundle#257]
How to define relay connection? i define  follow example but i got an error. Undefined index: relay-connection.
I checked on code generator, seem nothing about relay on there.
Or i missing something?

**Comment by mcg-web** [comment]
Hi, can you provide some more information please? What version are you using? A example of your implementation?

**Comment by bitcoinporn** [comment]
Hi,
I figure it out. I realize normalizer on "TypesConfiguration.php" .
I inject schema types on generator. I want to build standard Crud from entity.

**Comment by mcg-web** [comment]
I don't really get it, this fixed your issue or you still need help?

**Comment by mcg-web** [comment]
I'm closing this, feel free to reopen if needed...
