### ISSUE TITLE
[BUG] Missing service

### ISSUE THREAD

**Issue by Guikingone** [overblog/GraphQLBundle#260]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.9.4

Hi everyone, what's up? 

I've just updated my bundle installation and GraphiQL told me that a service is missing : 

```bash
The \"overblog_graphql.request_parser\" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.
```

I've tried to clear the cache and relaunch the update but the problem still there, does anyone have an idea about this problem? 

Thanks again for the help and have a great day :)

**Comment by renatomefi** [comment]
Hello @Guikingone,

Are you trying to use this as `$container->get('overblog_graphql.request_parser')`?
Also, what's your symfony version?

**Comment by Guikingone** [comment]
Hi @renatomefi, 

No, I don't use the container, I simply use the tags 'overblog.graphql_resolver' for my personal resolvers. 

Symfony version: 4.0.1.

**Comment by Besedin86** [comment]
@Guikingone what if you try to implement `Overblog\GraphQLBundle\Definition\Resolver\ResolverInterface` in your resolvers and remove its configuration in services ?

**Comment by Guikingone** [comment]
@Besedin86 Not better, the error stay the same.

For the tag, yes, I know, just a typo when I've written.

**Comment by mcg-web** [comment]
@Guikingone have you override the controller?

**Comment by Guikingone** [comment]
@mcg-web Nope, I only use the services approach. 

Here's a resolver for my images : 

```php
<?php

declare(strict_types=1);

/*
 * This file is part of the CyclePath project.
 *
 * (c) Guillaume Loulier <contact@guillaumeloulier.fr>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Resolvers;

use App\Interactors\ImageInteractor;
use Doctrine\ORM\EntityManagerInterface;
use App\Resolvers\Interfaces\ImageResolverInterface;

/**
 * Class ImageResolver
 *
 * @author Guillaume Loulier <contact@guillaumeloulier.fr>
 */
class ImageResolver implements ImageResolverInterface
{
    /**
     * @var EntityManagerInterface
     */
    private $entityManagerInterface;

    /**
     * ImageResolver constructor.
     *
     * @param EntityManagerInterface $entityManagerInterface
     */
    public function __construct(EntityManagerInterface $entityManagerInterface)
    {
        $this->entityManagerInterface = $entityManagerInterface;
    }

    /**
     * {@inheritdoc}
     */
    public function getImages(\ArrayAccess $arguments)
    {
        if ($arguments->offsetExists('id')) {
            return [
                $this->entityManagerInterface
                     ->getRepository(ImageInteractor::class)
                     ->findOneBy([
                          'id' => $arguments->offsetGet('id')
                     ])
            ];
        }

        return $this->entityManagerInterface
                    ->getRepository(ImageInteractor::class)
                    ->findAll();
    }
}
```

**Comment by mcg-web** [comment]
you using version 0.9.4 with Symfony 4.0.1?

**Comment by Guikingone** [comment]
@mcg-web Yes, as strange it can soud, I've just use ``composer update`` and here the informations given by composer info : 

```bash
overblog/graphql-bundle             v0.9.4  This bundle provides tools to build a GraphQL server in your Symfony App.
overblog/graphql-php-generator      v0.5.1  GraphQL types generator
```

**Comment by mcg-web** [comment]
this should not be possible :s

**Comment by mcg-web** [comment]
try to remove with `composer remove overblog/graphql-bundle` and require `composer require overblog/graphql-bundle:0.10.*`

**Comment by Guikingone** [comment]
Ok, way better, works great with ``composer require overblog/graphql-bundle:0.10.* overblog/graphql-php-generator:0.6.0``.

**Comment by mcg-web** [comment]
Normally you don't need to require the generator manually.
I don't really know what happen, I'll try to reproduce this. Thank you for your feedback :+1:

**Comment by Guikingone** [comment]
Yes, just tested the endpoint via Insomnia, way better, thanks for the fix but it seems strange that the 0.9.4 was allowed using Symfony 4.0.1 ...

**Comment by Guikingone** [comment]
@mcg-web If I don't require it, the update failed :/

**Comment by mcg-web** [comment]
so try to remove both and require only the bundle please

**Comment by Guikingone** [comment]
Ok, if I require the bundle after removing it, the installation succeeds.

**Comment by mcg-web** [comment]
Nice thank you @Guikingone, I'll work on the bug later, I'm closing this one :+1:
