### ISSUE TITLE
additional info in user errors

### ISSUE THREAD

**Issue by vbelorus** [overblog/GraphQLBundle#263]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.10.1

Hi there

**How to create custom exception (user error) and add additional info to it (not only change message)?**

I've tried to do custom exception class, but then this class moved to $previous in \GraphQL\Error\Error. 

I need to return to frontend fields and validation messages where validation errors were (wrong email format or phone number format for example). 

As workaround I extended and overrode default Error Handler and handleErrors method like this

```php
<?php

namespace App\GraphQL\Error;

use GraphQL\Error\Error;
use GraphQL\Error\UserError as GraphQLUserError;
use GraphQL\Executor\ExecutionResult;
use GraphQL\Error\Error as GraphQLError;
use Overblog\GraphQLBundle\Error\UserErrors;
use Psr\Log\LogLevel;

class ErrorHandler extends \Overblog\GraphQLBundle\Error\ErrorHandler
{
    /**
     * @param ExecutionResult $executionResult
     * @param bool $throwRawException
     * @throws \Exception
     */
    public function handleErrors(ExecutionResult $executionResult, $throwRawException = false)
    {
        $executionResult->setErrorFormatter(function ($e) {
            $formattedError = GraphQLError::formatError($e);

            /** @var Error $e */
            $prev = $e->getPrevious();

            if ($prev instanceof ValidationErrors) {
                $formattedError['validationErrors'] = $prev->formatValidationErrors();
            }

            return $formattedError;
        });
        $exceptions = $this->treatExceptions($executionResult->errors, $throwRawException);
        $executionResult->errors = $exceptions['errors'];
        if (!empty($exceptions['extensions']['warnings'])) {
            $executionResult->extensions['warnings'] = array_map([GraphQLError::class, 'formatError'], $exceptions['extensions']['warnings']);
        }
    }
}
``` 

But It might be not very good solution.

**Comment by mcg-web** [comment]
Hi,
Right now overriding the handler is the only way to do that, but we working on a solution to let user custom their errors without having to override.

**Comment by vbelorus** [comment]
@mcg-web Thank you, got it, appreciate the info.

**Comment by apoberez** [comment]
Hi,
@mcg-web something like this looks not bad:
https://medium.com/@tarkus/validation-and-user-errors-in-graphql-mutations-39ca79cd00bf

**Comment by mcg-web** [comment]
Thanks @apoberez this was already proposed in #256, I like this implementation and yes it can be the default behavior for the bundle. Anyway the true issue is the lake of easy way to customize the output errors section. That should be the first step to improve errors messages, next we can change our default behavior.

**Comment by mcg-web** [comment]
closing this in favor of #182
