### ISSUE TITLE
Strange cache behavior

### ISSUE THREAD

**Issue by Cydonia7** [overblog/GraphQLBundle#267]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.10.2

I'm using the `RequestExecutor` inside a PHPUnit test (using Symfony 4 and Flex). The first time, when cache is being generated, it works perfectly. After the first try, an error keeps occuring : 

```
RuntimeException: Type class for alias "Query" could not be load. If you are using your own classLoader verify the path and the namespace please.

Caused by
Error: Class 'Overblog\GraphQLBundle\__DEFINITIONS__\QueryType' not found
```

In the `var/cache/test/overblog/graphql-bundle/__definitions__/__classes.map`, I have the following:
```
<?php
return array (
  'Overblog\\GraphQLBundle\\__DEFINITIONS__\\PageInfoType' => __DIR__ . '/PageInfoType.php',
  'Overblog\\GraphQLBundle\\__DEFINITIONS__\\QueryType' => __DIR__ . '/QueryType.php',
  'Overblog\\GraphQLBundle\\__DEFINITIONS__\\RecipeType' => __DIR__ . '/RecipeType.php',
);
```

And the 3 files above exist and seem to contain valid content.

Am I doing something wrong?

**Comment by mcg-web** [comment]
Hi, can you try adding `static::$kernel->getContainer()->get('overblog_graphql.cache_compiler')->loadClasses(true);` in test setup.

**Comment by Cydonia7** [comment]
I don't know what changed since the last time but I can't reproduce the situation anymore, it works now for some reason. Thanks for your help, I'm closing this until I can replicate it.

**Comment by Roensby** [comment]
I've had this error message happen in production running version 0.15.3 and PHP 8.1/Symfony 6.3.
Unfortunately not reproducible and happened only once so far.
