### ISSUE TITLE
How to use the invoker method for resolver?

### ISSUE THREAD

**Issue by sylfabre** [overblog/GraphQLBundle#268]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.10

First, thank you for this nice bundle!

I managed to make some working code for the aliased resolver methods as described at https://github.com/overblog/GraphQLBundle/blob/master/Resources/doc/definitions/resolver.md but I'm struggling to use the invoker way: I think it comes from my schema but I don't know where I'm wrong as there is no example.

Moreover, the doc says that _This way SayHello resolver can be accessed with App\GraphQL\Resolver\Greetings_ but this method `SayHello` is nowhere described nor used in the doc :(

**Comment by mcg-web** [comment]
Hi @sylfabre,

here how you can call resolver:
- with invoker '@=resolver("App\\GraphQL\\Resolver\\Greetings", [args['name']])'
- with method '@=resolver("App\\GraphQL\\Resolver\\Greetings::sayHello", [args['name']])'
- with alias '@=resolver("say_hello", [args['name']])'

**Comment by sylfabre** [comment]
@mcg-web merci !

**Comment by mcg-web** [comment]
Good luck and if need more help you can also meet us on slack.

**Comment by sylfabre** [comment]
@mcg-web actually it's `@=resolver("App\\\\GraphQL\\\\Resolver\\\\Greetings::sayHello", [args['name']])` ie `\` x4

**Comment by mcg-web** [comment]
@sylfabre  with simple or double quotes wrapping all the expression `@=resolver(...)` ?

**Comment by sylfabre** [comment]
@mcg-web `resolve: "@=resolver('App\\\\GraphQL\\\\Resolver\\\\UserResolver::resolve', [context])"`

**Comment by mcg-web** [comment]
replace double quote by simple quote `resolve: '@=resolver('App\\GraphQL\\Resolver\\UserResolver::resolve', [context])'`
