### ISSUE TITLE
[documentation] Improve « Type inheritance » doc with inline fragments

### ISSUE THREAD

**Issue by Kocal** [overblog/GraphQLBundle#269]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.11

As said on [a Slack thread](https://symfony-devs.slack.com/archives/C7PE69PU3/p1515429442000727), I will improve the [Type inheritance documentation](https://github.com/overblog/GraphQLBundle/blob/master/Resources/doc/definitions/type-inheritance.md) by adding examples that use [inline fragments](http://graphql.org/learn/queries/#inline-fragments).

**Comment by mcg-web** [comment]
Thank you again @Kocal :+1:
