### ISSUE TITLE
Type class could not be loaded

### ISSUE THREAD

**Issue by SebScoFr** [overblog/GraphQLBundle#274]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Version/Branch   | 0.10.2

Symfony version: 4.0

For some strange reasons, today I'm randomly experiencing this error:
```
Type class for alias \"MyType\" could not be load. If you are using your own classLoader verify the path and the namespace please.
```

It would work fine for a while, and then break again with this 😕
When and why exactly would this error be triggered?

**Comment by mcg-web** [comment]
Can replace me in the context please? Is the related to #274?

**Comment by SebScoFr** [comment]
Apologies @mcg-web, this seemed to be related with Symfony caching issues, which also explains the randomness of it.
This issue can be closed.

**Comment by mcg-web** [comment]
Ok thanks for feedback
