### ISSUE TITLE
GraphiQL authentication

### ISSUE THREAD

**Issue by enumag** [overblog/GraphQLBundle#280]
We added an authentication layer to our GraphiQL. The schema is still public but some (well most in our case) mutations and queries require the user to be authenticated and authorized to make the request.

Of course now out GraphiQL doesn't really work. Most queries and mutations simply fail with "Authentication Required" error. Any tips how to make it work again? How do you solve this in your applications?

**Comment by mcg-web** [comment]
Have you try [adding authentication headers](https://github.com/overblog/GraphiQLBundle/blob/master/Resources/doc/custom-http-headers.md) ?

**Comment by enumag** [comment]
I'm guessing that [this](https://github.com/overblog/GraphQLBundle/blob/0.10/Resources/doc/definitions/graphiql/custom-http-headers.md) is the correct version of that page for the 0.10 version. With the configuration you linked I'm getting `There is no extension able to load the configuration for "overblog_graphiql"`. If I understand it correctly the GraphiQLBundle is not needed now but will be in v0.11, right?

**Comment by mcg-web** [comment]
Right! GraphiQL comes out of the box in 0.10 but move to a dedicate repository in 0.11.

**Comment by enumag** [comment]
Anyway it works now. Thanks!
