### ISSUE TITLE
Quick Start issues and suggested improvements

### ISSUE THREAD

**Issue by bartosz-maciaszek** [overblog/GraphQLBundle#285]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes/no
| Version/Branch   | 0.10.3

Hey,

I'm going through the [Quick Start guide](https://github.com/overblog/GraphQLBundle/blob/master/Resources/doc/definitions/quick-start.md) using Symfony4 and flex, but I ran into a couple of issues:

1. Changing `type: yaml` to `type: graphql` causes an exception: 

` [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]                                                        
  The value "graphql" is not allowed for path "overblog_graphql.definitions.mappings.types.0.type". Permissible values: "yaml", "xml" `

2. Because of missing types, I'm getting `Unknown type with alias \"Query\" (verified service tag)` exception when trying to do anything. Since the default configuration specifies that type, it would be great if it was included in the package or at least described in the doc how to create it to get a working graphql server easily.

3. After adding the snippet below to `config/packages/graphql.yaml`:

```
            resolver_maps:
                - App\Resolver\MyResolverMap
```

I'm getting another exception saying:

`[Symfony\Component\Yaml\Exception\ParseException]                                                             
  A colon cannot be used in an unquoted mapping value at line 6 (near "        - App\Resolver\MyResolverMap"). `

4. `Overblog\GraphQLBundle\Resolver\ResolverMap` class that you suggest to use when creating `App\Resolver\MyResolverMap` does not exist. Maybe it used to exist in the previous versions of the bundle and the documentation is just outdated?

Any help would be greatly appreciated!

**Comment by mcg-web** [comment]
Hi,
this feature is available only in dev version 0.11-dev (master branch), 0.10 doc can be found [here](https://github.com/overblog/GraphQLBundle/tree/0.10)

**Comment by bartosz-maciaszek** [comment]
Thanks for a quick reply, I'll give `dev-master` a go.

**Comment by mcg-web** [comment]
All feedback is welcome :+1:
