### ISSUE TITLE
Reporting validation errors

### ISSUE THREAD

**Issue by arnaud-lb** [overblog/GraphQLBundle#287]
| Q                | A
| ---------------- | -----
| Feature request? | yes

It would be interesting to be able to report validation errors that occurred during a mutation, and especially to specify the path/field related to each error. This would allow a client to display errors next to the form fields that are invalid, for example.

Right now, errors are formatted like the JSON document bellow. The only part that can be changed as a GraphQLBundle user is the error message. It's meant to be a human readable message, and not something that a program could use to make decisions, so an API client can not use it to decide where to display the message in a form.

In order to give more informations to API clients, it would be great to be able to add custom attributes to errors, and/or to append components to the path attribute.

_Example of how errors are formatted currently:_

``` json
{
  "errors": [
    {
      "message": "Error message",
      "locations": [
        {
          "line": 4,
          "column": 3
        }
      ],
      "path": [
        "someMutation"
      ]
    }
  ],
  "data": {
    "...": null
  }
}
```

## Possible solutions

Given the mutation:

```
createUser(input: CreateUserInput!): CreateUserPayload

input CreateUserInput {
    username: String!
    email: String!
}
```

And the request:

```
mutation CreateUserMutation(
  $input: CreateUserInput!
) {
  createUser(data: $input) {
    user {
      ID, username, email
    }
  }
}
```

If some field is invalid, I can throw a UserError, and the message of the exception is return to the client. However, the client can not tell if the error is about the username or the email.

One way to tell the client which field is concerned by an error would be to append components to the path attribute:

``` php
<?php

throw new UserError("Invalid email address", ['email']);
```

``` json
{
  "errors": [
    {
      "message": "Error message",
      "path": [
        "someMutation",
        "email"
      ],
```

However I'm not sure that it's safe to change the value of this field. 

An other solution would be to be able to add custom attributes:

``` php
<?php

throw new UserError("Invalid email address", ['type' => 'validation_error', 'field' => 'email']);
```

``` json
{
  "errors": [
    {
      "message": "Error message",
      "type": "validation_error",
      "field": "email",
```

Is this a problem that other users have tried to solve ? What do you think of the proposed solutions ?

**Comment by mcg-web** [comment]
Hi,
the bundle error formatting is simple but you can easily override this behavior, see [custom error formatting](https://github.com/overblog/GraphQLBundle/blob/master/Resources/doc/error-handling/index.md#custom-error-formatting), anyway we are not close to modifications, PR is welcome.

**Comment by arnaud-lb** [comment]
Hi

Thanks you. I was able to implement this with the graphql.error_formatting event.

**Comment by sylfabre** [comment]
@arnaud-lb I'm looking to implement the same for my project.
I've read https://medium.com/@tarkus/validation-and-user-errors-in-graphql-mutations-39ca79cd00bf which is quite interesting.
How have you implemented the handling of theses errors?
