### ISSUE TITLE
Resolvers context argument not mutable

### ISSUE THREAD

**Issue by ste93cry** [overblog/GraphQLBundle#294]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | yes
| RFC?             | no
| Version/Branch   | master

The callback of the resolvers can take as input an array that represents contextual data passed to them. In the Javascript implementation of GraphQL the `context` argument is an `Object` which users can use whathever they want. However, in this bundle its type is a plain PHP `array` which is not even passed by reference, so nothing can't be persisted inside it (e.g. cache some data to share between resolvers) and this makes it completely useless imho. Instead, it should be some kind of object (it could even implement the `ArrayAccess` interface) to mimic the behaviour of the Javascript official library. Magento 2 is adding support for GraphQL and they pass an instance of an object implementing a custom interface: `ResolverContextInterface`

**Comment by mcg-web** [comment]
Hi, `context` is now an `ArrayObject` in `v0.11-dev`, have you updated to latest master version? We also added event to initialized context.

**Comment by ste93cry** [comment]
Ops, I didn't see that this was already changed in `0.11`. I think it would be better if an interface was used so that the implementation can easily be swapped out, but this is anyway a progress

**Comment by mcg-web** [comment]
I'm not against an interface , a PR will be welcome. Thanks anyway for feedback :+1:

**Comment by mcg-web** [comment]
Closing this right now because bundle actually answer to initial need. If interface is really a need for you don't hesitate to open an issue or/and a PR.
