### ISSUE TITLE
Generating constants for type names, fields

### ISSUE THREAD

**Issue by arnaud-lb** [overblog/GraphQLBundle#300]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no

Sometimes we have to write the name of GraphQL types as strings in our code, most frequently in type resolvers.

I believe that having PHP constants that refer to the GraphQL types would help keeping the code in sync with the GraphQL schema, and would also avoid typos.

It would be great if the generated Type classes had a constant like this:

```php
/**
 * THIS FILE WAS GENERATED AND SHOULD NOT BE MODIFIED!
 */
final class UserType extends ObjectType implements GeneratedTypeInterface
{
    const NAME = 'User';
```

Sometimes I also need to refer to some field names in my code, most frequently for mutations or subscriptions. It would be great if the generated type classes exported their field names in constants:

```php
    const FIELD_SIGNUP = 'signup';
    const FIELD_ACTIVATE = 'activate';
```

What do you think ? I'm willing to make a PR, if you agree.

**Comment by mcg-web** [comment]
I think fields constants can be added as helpers but should not be actually use directly in types classes to don't slow down schema execution performance. We can start by adding `NAME` in a first place. PR is welcome :+1:.

**Comment by mcg-web** [comment]
`NAME` constant seem to help in a first place thanks again, if you still the need of adding fields constant make it know we will reopen this PR
