### ISSUE TITLE
Type class for alias "Query" could not be load

### ISSUE THREAD

**Issue by progotman** [overblog/GraphQLBundle#301]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.11.0

I ran into a problem. When i run **composer install** or **bin/console cache:clear** with empty cache directory. Then GraphQL endpoint returned 500 http code with message:
> **Type class for alias "Query" could not be load. If you are using your own classLoader verify the path and the namespace please.** 

I could not understand what was going on. Then I found out the reason for this problem.
``` php
namespace Overblog\GraphQLBundle\CacheWarmer;
...
class CompileCacheWarmer implements CacheWarmerInterface
{
...
     public function warmUp($cacheDir)
     {
          $this->typeGenerator->compile(TypeGenerator::MODE_WRITE | TypeGenerator::MODE_OVERRIDE);
     }
}
```
Please note the variable **cacheDir**. Сan take the value, eg for  dev environment **/var/cache/dev** and 
**/var/cache/de_**. These are the features of the Symfony cache clear command. 

The cache is warmed up in the temporary directory **de_**, then there is a deletion of **dev(old cache)** and renaming **de_** to **dev**.

To fix this, you need to make the following changes:
``` php
namespace Overblog\GraphQLBundle\CacheWarmer;
...
class CompileCacheWarmer implements CacheWarmerInterface
{
...
     public function warmUp($cacheDir)
     {
            $this->typeGenerator
               ->setCacheDir($cacheDir . '/overblog/graphql-bundle/__definitions__')
               ->compile(TypeGenerator::MODE_WRITE | TypeGenerator::MODE_OVERRIDE);
     }
}
```

**Comment by mcg-web** [comment]
Hi @progotman thank you for the report and the fix! The cache path is configurable so we should try to don't loose this. Do you want to open a fast PR with you fix? I'll complete it later.

**Comment by progotman** [comment]
@mcg-web I'll try to find solution with configuration. If everything will be ok, I'll make PR.
