### ISSUE TITLE
TypeGenerator::processConfigs seems to run on every page load and is slow

### ISSUE THREAD

**Issue by ruudk** [overblog/GraphQLBundle#307]
| Q                | A
| ---------------- | -----
| Bug report?      |no
| Feature request? |no
| BC Break report? |no
| RFC?             |no
| Version/Branch   | 0.10

We are using GraphQLBundle for a very long time. With Blackfire we did some profiling and discovered that TypeGenerator::processConfigs takes 40ms on every request.

See screenshot:
<img width="678" alt="screen shot 2018-04-06 at 11 57 54" src="https://user-images.githubusercontent.com/104180/38415581-3d160678-3992-11e8-8b1d-b36ce52aab35.png">

Even on pages where we don't do anything with GraphQL (like plain Symfony controllers).

What could this be? Does upgrading to 0.11 solve these issues?

**Comment by mcg-web** [comment]
Normally 0.11should fix this but any if this is the case with 0.10 should give it a fix

**Comment by ruudk** [comment]
Solved by upgrading to 0.11
