### ISSUE TITLE
Add a benchmark tool to follow performance

### ISSUE THREAD

**Issue by mcg-web** [overblog/GraphQLBundle#309]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.11 / 0.12

**Comment by Kocal** [comment]
Since #366 has been merged, should we close this ticket?
Or are you planning to do other PR referencing this ticket?

**Comment by mcg-web** [comment]
Yes we can close this one. Thank you!
