### ISSUE TITLE
Change documentation "input-object"

### ISSUE THREAD

**Issue by god1dog** [overblog/GraphQLBundle#316]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.11.0

https://github.com/overblog/GraphQLBundle/blame/v0.11.0/Resources/doc/definitions/type-system/input-object.md#L8

Apparently there should be not "type" -> "input"

**Comment by mcg-web** [comment]
Thank you, can you submit a fast PR for this please?

**Comment by god1dog** [comment]
#317
