### ISSUE TITLE
Question: Mutation with GraphQL schema language

### ISSUE THREAD

**Issue by andrewprofile** [overblog/GraphQLBundle#328]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.11

How do I use the mutation with GraphQL schema language because I get an error "Operation definition is not supported right now". when I defined *.graphql:

```js
type Language {
    code: ID!
    name: String!
    createdAt: DateTime!
    updatedAt: DateTime!
}

input NewLanguage {
    code: ID!
    name: String!
}

mutation CreateNewLanguage($newLanguage: NewLanguage!) {
    newLanguage(language: $newLanguage) {
        code
        name
    }
}
```

**Comment by mcg-web** [comment]
Hi this part
mutation CreateNewLanguage($newLanguage: NewLanguage!) {
    newLanguage(language: $newLanguage) {
        code
        name
    }
}
Is a query not a type definition. You should define your query and mutation as type then  provide their names with bundle configuration.

**Comment by mcg-web** [comment]
```graphql
type Language {
    code: ID!
    name: String!
    createdAt: DateTime!
    updatedAt: DateTime!
}

input NewLanguage {
    code: ID!
    name: String!
}

type RootMutation {
    CreateNewLanguage(newLanguage: NewLanguage!): Language!
}

type RootQuery {
  language: Language!
}
```

```yaml
overblog_graphql:
    definitions:
      schema:
        query: RootQuery
        mutation: RootMutation
```
After you should define ResolverMap

**Comment by andrewprofile** [comment]
Thank you very much, earlier I misinterpreted your answer and in the meantime I came up with it myself, although it seems to me that an example would be useful in the documentation for the version based on GraphQL schema language.

**Comment by mcg-web** [comment]
Yeah, it seems it missing a complet example, feel free to contribute anyway, if you see how this can be improve :+1:

**Comment by Knudian** [comment]
Instead of making a new issue, I place my piece of junk here.

Couldn't be possible to add a bit more infos in all code samples, or have a dummy project somewhere?
I mean, a simple line comment with the file name. As simple as that.

(Giving, or setting up through the recipe, a default directory structure would also be a nice point)

**Comment by mcg-web** [comment]
We working on a [demo](https://github.com/overblog/GraphQLBundleDemo) but documentation take a lot of time. The more feedback we have the easier the doc improvement will be.

**Comment by Kocal** [comment]
I will try to work on some documentation improvments for this page [GraphQL schema language](https://github.com/overblog/GraphQLBundle/blob/master/Resources/doc/definitions/graphql-schema-language.md).

By the way @mcg-web, when we define our schema with GraphQL, it is not possible to: 
- define field access control
- define field visibility

right?

**Comment by mcg-web** [comment]
Yes acl management is missing, must implement it yourself right now, while waiting for 0.12...

**Comment by Kocal** [comment]
Okay thanks, that was just a question for the documentation.

Well, we can't wait to migrate our ~70 types, ~70 input objects and ~85 mutations from `.yml` to `.graphql` files (cc @tristanbes) 🤣
