### ISSUE TITLE
API without Query

### ISSUE THREAD

**Issue by danaki** [overblog/GraphQLBundle#334]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.11.0

My API is for mutations only. Can't configure the bundle without using Query:
1. If I do not configure Query, getting this error: "Unknown type with alias "Query" (verified service tag)"
2. If I leave Query's "fields" empty, getting this error: "The path overblog_graphql_types.Query._object_config.fields should have at least 1 element(s) defined."
3. If I omit query from schema definitions, I'm getting this error: "Schema query must be Object Type but got: NULL"

**Comment by mcg-web** [comment]
Hi, this is not a bug because a schema always require a valid query. This is part of the specifications http://facebook.github.io/graphql/October2016/#sec-Initial-types.

**Comment by danaki** [comment]
The specification says that Query type must be provided, it doesn't say there must be at least 1 query defined. Thus error "Unknown type with alias "Query"" after fresh composer install will be avoided too. Imagine a bundle that produces errors in your project just after you install it using shipped default config.

**Comment by mcg-web** [comment]
> it doesn't say there must be at least 1 query defined.

the specs says that schema should provide a valid Object query, it also says that an object require at least one field http://facebook.github.io/graphql/October2016/#sec-Object-type-validation

> Thus error "Unknown type with alias "Query"" after fresh composer install

I agree is annoying and need a fix. This issue is related to flex recipe that does not allow example files.

I maybe just don't get it, so if this is the case provide some more examples please

**Comment by danaki** [comment]
Well my app has just signup and login mutations. It's not a real app of course. Thus I was forced to create a "ping" Query to have at least one resolver. Not a big deal, but surprises a lot. Later I will share the repo.

**Comment by danaki** [comment]
Here is my [toy project](https://github.com/danaki/symfony-graphql-users-api-starter) I was forced to create an empty PingResolver because without defined Query it won't work.
