### ISSUE TITLE
Error while multiple mutations stop execution

### ISSUE THREAD

**Issue by maximecolin** [overblog/GraphQLBundle#346]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Feature request? | maybe
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.11.1

Hi. I'm experiencing a strange behavior and I'm not sure it's normal or not.

When I perform multiple queries in the same http request and one of the queries failed (typically, the resolver throw an exception), 

```graphql
{
   fail: Foobar(uuid: "abc") { uuid }
   success: Foobar(uuid: "efg") { uuid }
}
```

then two possible case :
- my query return type is not-nullable, then the resolution is stoped and my response will contain an empty `data` and 1 `error`.

```json
{
   "errors": [{ "message": "Foobar error", "path": ["fail"] }],
   "data": []
}
```

- or, **my query return type is nullable, then the resolution continue and my response will contain the `data` of the others queries, 1 null `data` and 1 `error` for the failed queries**.

```json
{
   "errors": [{ "message": "Foobar error", "path": ["fail"] }],
   "data": {
        "fail": null,
        "success": { "uuid": "efg" }
   }
}
```

I thought i will have the same behavior with multiple mutation but when one of the mutations failed the others ones are not resolved, no matter the return types are nullable or not.

```graphql
mutation {
   fail: CreateFoobar(uuid: "abc") { uuid }
   success: CreateFoobar(uuid: "efg") { uuid }
}
```

With not nullable return type :

```json
{
   "errors": [{ "message": "Foobar error", "path": ["fail"] }],
   "data": []
}
```

With nullable return type :

```json
{
   "errors": [{ "message": "Foobar error", "path": ["fail"] }],
   "data": {
        "fail": null,
        "success": null
   }
}
```

The second mutation is not executed.

What i expect :

```json
{
   "errors": [{ "message": "Foobar error", "path": ["fail"] }],
   "data": {
        "fail": null,
        "success": { "uuid": "efg" }
   }
}
```

I read [this article](https://techblog.commercetools.com/modeling-graphql-mutations-52d4369f73b1) about mutations and this seems to match what i expect :

> Also keep in mind the difference between the nullable and not-null mutation field types. According to the [GraphQL error propagation rules](http://facebook.github.io/graphql/October2016/#sec-Errors-and-Non-Nullability), if an error is raised during the resolution of a not-null field, then the whole object is considered unresolved and the error bubbles up. Since mutation fields are always resolved sequentially, this provides us a mechanism to control how mutation query execution should react in case of a failed mutation field.
> 
> In our case we decided to make all top-level mutation fields nullable. This means that if one mutation field fails for some reason, then subsequent sibling mutation fields will still execute.
> 
> An alternative would be to disallow this behaviour and make all fields not-null. In this case query execution will stop on the first failed mutation field. Yet another alternative would be to allow client to decide the error handling behaviour and provide both field variations in the schema.

If i understand correctly, in case of multiple mutations, if return types are not nullable, the execution will stop a the first error, if return types are nullable, the execution will continue and all mutations will be processed, which is not the case currently.

Can you tell me what behavior is the right one ? Is it possible to execute all mutations event if one of them raise an exception ?

**Comment by mcg-web** [comment]
Hi, It seems you right , have you try directly using the webonyx lib ? Maybe @vladar can give us a fast answer on the expected behavior ?

**Comment by maximecolin** [comment]
I just tried with webonyx and it works as expected. I modify this [example](https://github.com/webonyx/graphql-php/tree/master/examples/00-hello-world) to throw exception in case of x = 0. See https://gist.github.com/maximecolin/18e045dea355cbca68138ee82c172ce4.

```
$ curl http://localhost:8080 -d '{"query": "mutation { sum1: sum(x: 0, y: 2), sum2: sum(x: 2, y: 2) }" }'
{"errors":[{"message":"Internal server error","category":"internal","locations":
[{"line":1,"column":12}],"path":["sum1"]}],"data":{"sum1":null,"sum2":4}}
```

As expected the second mutation is executed and its return is present in the response.

**Comment by mcg-web** [comment]
Ok so it's a bug, i will try to fix this.

**Comment by mcg-web** [comment]
It work as expected for me in above PR, can you tell me please what versions of vendors `overblog/*` and `webonyx/graphql-php` with a composer info?

**Comment by maximecolin** [comment]
```
overblog/graphql-bundle: v0.11.0
overblog/graphql-php-generator: v0.7.2
webonyx/graphql-php: v0.11.5
```

I'll try updating these dependencies.

**Comment by maximecolin** [comment]
I updated my dependencies but i've still the same result. The first mutation throw an exception, the second mutation is not executed and i got null result for both of them.

```
overblog/graphql-bundle: v0.11.1
overblog/graphql-php-generator: v0.7.2
webonyx/graphql-php: v0.11.6
```

Can something else influences the result ?

**Comment by mcg-web** [comment]
I try with same versions and still seems to work for me. Can try to use to different mutation please like

```graphql
mutation {
  fail: failOptional
  success: success
}
```

**Comment by maximecolin** [comment]
Ok, I finally succeed to make it work. I found out others mutations failed too because of a command bus middleware closing my entity manager when the first mutation failed. Only the first error appeared in the response so it take me times to find out. I fix this and now it behave like expected. Thanks @mcg-web. I think you can close the issue.
