### ISSUE TITLE
Human-readable documentation

### ISSUE THREAD

**Issue by Destroy666x** [overblog/GraphQLBundle#352]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | x.y.z

Hello,
my proposal is to have a console command to generate HTML output with type definitions, mutations and resolvers linked to eachother. Something similar to `graphql:debug` but with data like arguments and possibility to move through various nested types etc. quickly.

Why? Easier job for front ends primarily.

**Comment by mcg-web** [comment]
Hello,
Just by curiosity why GraphiQL documentation does not make the job?

**Comment by Destroy666x** [comment]
Kind of, but not fully, some useful info like resolvers are missing.

**Comment by mcg-web** [comment]
Ok thanks for answer, do you want to submit a PR for that?

**Comment by Destroy666x** [comment]
Maybe this weekend, I'll see if I have time.

**Comment by Destroy666x** [comment]
Good idea, didn't know that one. Could use that + a plugin for resolvers I guess

**Comment by mcg-web** [comment]
Seems that you got a way to solve you issue.
