### ISSUE TITLE
Mutation example for Symfony 4

### ISSUE THREAD

**Issue by defixje** [overblog/GraphQLBundle#357]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | all

Hi, i was wondering if there was an example how to use this Bundle in Symfony 4, but then the mutation part? I only get the Query part working, but can't find any examples to implement the mutation part.

Thanks!

**Comment by mcg-web** [comment]
Hi, a mutation is a just a query where you do some persistent stuffs in your resolvers, so you can use the same examples. But maybe I'm missing something to answer correctly to your question, just help me get it if this is the case :+1:

**Comment by Kocal** [comment]
@defixje I just made a PR that should improves mutation documentation. Can you take a look to #359 and tell me if it's fine for you ?

**Comment by mcg-web** [comment]
Example added thank you @Kocal
