### ISSUE TITLE
How to retrieve data like from symfony request

### ISSUE THREAD

**Issue by webmake** [overblog/GraphQLBundle#362]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Version/Branch   | 0.11.4

Is it possible to treat with submited data like injecting `request_stack`, and then getting data from request?

```
    App\ExampleDataProvider:
        arguments:
            $requestStack: '@request_stack'
```
```
class ExampleDataProvider
{
    private $request;

    public function __construct(RequestStack $requestStack)
    {
        $this->request = $requestStack->getCurrentRequest();
    }

    public function getSpecifiedData(): string
    {
        return $this->request->get('specifiedData');
    }
}
```
Because now request contains only graphql not parsed string (` $this->request->getContent()` gets 
`{"query":"mutation {\n\tmutationExample(input: {specifiedData: \"real data\"}  ) {\n\t\tresponseToGet\n\t}\n}\n"}`)

**Comment by mcg-web** [comment]
You can inject directly to you resolver using expression language like this `resolve: '@=resolver('foo', [serv('request_stack')])'`

**Comment by webmake** [comment]
But it requires `foo` concrete tag (service), which can differ with every different scope within mutations when trying to resolve. Moreover using this can be performance issue, because every service would try to resolve by it's need, I expect something to be cached, like request itself has, or putted data into container. No matter how we look, there is plain array. For example we can deal with json input, form input despite the format, there would be still accessible variables

**Comment by akomm** [comment]
"Sumitted data" is kind of a huge context to pick from you gave. What is submitted data? 

The whole request? You can try json_decode the body, after injecting it via request_stack.

Or in a mutation the arguments? arguments into your resolver. `args`

Query information/ast? check resolveInfo. `info`

see in the variable [descriptions table](https://github.com/overblog/GraphQLBundle/blob/61bba982671afd3e094c1510f70f8e40ae1669d1/docs/definitions/expression-language.md)

**Comment by webmake** [comment]
Problem is, parsing costs a lot, so my intent was to reuse once it was parsed whenever I need
