### ISSUE TITLE
Subscription type ?

### ISSUE THREAD

**Issue by CocoJr** [overblog/GraphQLBundle#363]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | ?

Hi,

There is any way to use the GraphQL Subscription type? I found nothing about this in the documentation / repository.

**Comment by mcg-web** [comment]
Hi, subscription is not implement in webonyx lib right now since this bundle is just a overlay to this lib it a more difficult to implement this. Here some discussions about that https://github.com/webonyx/graphql-php/issues/9 or https://github.com/overblog/GraphQLBundle/issues/155.

**Comment by CocoJr** [comment]
Ok sorry, is duplicate of #155 ... I try to implement the Siler solution ;)

**Comment by mcg-web** [comment]
Feel free to continue discussion in #155 ;)
