### ISSUE TITLE
Parser possibly loses request data

### ISSUE THREAD

**Issue by ardi-n** [overblog/GraphQLBundle#38]
Unless I do something wrong, when I send data in a request body `Parser` seems to lose it. See what happens with passed `$data` here: https://github.com/overblog/GraphQLBundle/blob/master/Request/Parser.php#L82

**Comment by mcg-web** [comment]
When using request body Parser you must declare a correct `content-type` header (application/json or application/graphql).
**application/graphql**: raw graphql query should be given in the request body, `variables` and `operationName` can be define GET query string.

**application/json**: all variables can be given in a json in the request body 
```js
{
  "query": "Your Graphql query",
  "variables": {"id": 20, "other": "value"},
  "operationName": "..."
}
```

**Comment by ardi-n** [comment]
When doing a mutation, I send parameters with `multipart/form-data` and parser lands here: https://github.com/overblog/GraphQLBundle/blob/master/Request/Parser.php#L63.
But this data is lost in a call to next method.

**Comment by mcg-web** [comment]
The Parser track only 3 parameters (query, variables and operationName). You can access other parameters by passing request to you mutation resolver using expression language `"@=mutation('my_mutation', [value, user, request, info])"` or using DI to inject the `request_stack`...

**Comment by ooflorent** [comment]
@ardi-n By accessing `request` you can read sent files.

```php
$request->files->get('picture')
```
