### ISSUE TITLE
We cannot Use PHP Magic calls due to the way `PropertyAccessor` is created in Resolver class

### ISSUE THREAD

**Issue by AdelBachene** [overblog/GraphQLBundle#380]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? |no
| RFC?             | no
| Version/Branch   | 0.11

Hi Guys,

I was trying to implement translation in my Doctrine entities using this bundle [KnpLabs/DoctrineBehaviors](https://github.com/KnpLabs/DoctrineBehaviors#proxy-translations) and I had to use PHP magic function __call 

```php
    /**
     * @param string $method
     * @param array $args
     * @return mixed
     */
    public function __call(string $method, array $args) {
        return $this->proxyCurrentLocaleTranslation($method, $args);
    }
```

Here I noticed that your bundle is using `"symfony/property-access": "^3.4 || ^4.0"`. Which causes an issue on the Resolver level, more specifically when you are creating Property Accessor where it's instantiating a new `createPropertyAccessorBuilder` class without passing any arguments for configuration where by default `magicCall` is set to false.

in your Resolver.php you have the next static method:

```php
  private static function getAccessor()
    {
        if (null === self::$accessor) {
            self::$accessor = PropertyAccess::createPropertyAccessor();
        }
        return self::$accessor;
    }
```

and the class `PropertyAccess` is represented as:

```php
final class PropertyAccess
{
    /**
     * Creates a property accessor with the default configuration.
     *
     * @return PropertyAccessor
     */
    public static function createPropertyAccessor(): PropertyAccessor
    {
        return self::createPropertyAccessorBuilder()->getPropertyAccessor();
    }
    public static function createPropertyAccessorBuilder(): PropertyAccessorBuilder
    {
        return new PropertyAccessorBuilder();
    }
    /**
     * This class cannot be instantiated.
     */
    private function __construct()
    {
    }
}
```

so this calls is calling `new PropertyAccessorBuilder()` without passing any parameters

> class PropertyAccessorBuilder
> {
>     private $magicCall = false;

which means `$magicCall` will be always false.

this issue can be seen as a bug or as a new feature depending on our context
thank you for the effort that you made on the bundle and we would be happy to see in the future the possibility to configure this.

I could imagine something like this in services.yaml

```yaml
    property_accessor:
        class: Symfony\Component\PropertyAccess\PropertyAccessorBuilder
        calls:
          - method: enableMagicCall
    Overblog\GraphQLBundle\Resolver\Resolver:
        arguments:
          - property_accessor
```

**Comment by mcg-web** [comment]
Hi, 
thank you, for reporting this! Making default `Resolver` is a very good idea but this is a feature not a bug in our context. This will be implement in new version. You can easily fix your issue right now by changing the default resolver using parameters:

```yaml
parameters:
    overblog_graphql.default_resolver: ['App\My\Resolver', 'defaultFieldResolver']
```

**Comment by mcg-web** [comment]
The external default field resolver will be replaced by generated code on compile time, config will leave more hand on how to manage all these #406

**Comment by AdelBachene** [comment]
@mcg-web Thank you
