### ISSUE TITLE
Passing integer to GlobalId causes "Malformed UTF-8 characters" error

### ISSUE THREAD

**Issue by pascaldevink** [overblog/GraphQLBundle#381]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.11.5

TLDR; When passing an integer to an `ID` field, an `InvalidArgumentException` is triggered with the message "Malformed UTF-8 characters, possibly incorrectly encoded".

With a schema like this:
```graphql
type Query {
  user(id: ID!): User
}

type User {
  id: ID
  name: String
}
```
It can be seen that the id of a user needs to be a global ID. This works if an actually base64 encoded global id is passed.

However, when querying like this:
```graphql
query {
  user(id: 1033231) {
    name
  }
}
```
The `Overblog\GraphQLBundle\Relay\Node\GlobalId` does not check the outcome, and uses the resulting utf character as type. This trips the resolver in a later stage, resulting in an unhandled `InvalidArgumentException` with the message "Malformed UTF-8 characters, possibly incorrectly encoded".

I'm not entirely sure where the responsibility lies for checking/handling this. Maybe the `GlobalId` can throw an error if there is no id, or if the type consists of non-ascii values?

**Comment by mcg-web** [comment]
GlobalId should be use only for global id entry `base64_encode('Blog:15')` for example.

**Comment by pascaldevink** [comment]
yes, obviously, but we don't always control the input from our clients, and this actually just happened to us 😄

**Comment by mcg-web** [comment]
You should maybe use a custom method to check if GlobalId is a string before trying to decode it.

**Comment by mcg-web** [comment]
I'm closing this, if needed don't hesitate to continue to ask questions here.
