### ISSUE TITLE
(QUESTION ) : GraphQL schema language type inheritance

### ISSUE THREAD

**Issue by nckenn** [overblog/GraphQLBundle#383]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | x.y.z

Hi type inheritance is supported on your .yaml, but how about on .graphql?

**Comment by mcg-web** [comment]
Hi, this is not implement right now. But you can use decorator (yaml) combine with graphql schema language.

**Comment by mcg-web** [comment]
Closed this but you can continue the discussion here :+1:
