### ISSUE TITLE
Error when using GraphQL schema language

### ISSUE THREAD

**Issue by enumag** [overblog/GraphQLBundle#393]
I'd like to simplify my application by defining types using the [GraphQL schema language](https://github.com/overblog/GraphQLBundle/blob/master/docs/definitions/graphql-schema-language.md) and implementing a [ResolverMap](https://github.com/overblog/GraphQLBundle/blob/master/docs/definitions/resolver-map.md). Unfortunately I'm getting an error `Unknown type with alias "Query" (verified service tag)`.

Here is what I did:

- Used `bin/console graphql:dump-schema --format=graphql` to dump my current schema based on Symfony services.
- Moved the generated file to `config/graphql/schema.types.graphql`.
- Deleted the classes defining the old schema.
- Deleted `/var/cache`.

Of course my main graphql.yaml still contains this:

```
overblog_graphql:
    # ...
    definitions:
        # ...
        schema:
            query: Query
            mutation: Mutation
```

I didn't implement the ResolverMap yet but that should be ok - for now I simply want to have introspection queries up and running. Running any actual query would of course fail without ResolverMap.

As far as I can tell from the documentation this should be everything but I'm still getting the error as mentioned above.

Can you give me some advice why the Query type is not found despite being defined in `config/graphql/schema.types.graphql`? Do I need to do something else in order to load that file?

**Comment by mcg-web** [comment]
Try replacing thess [line in the bundle](https://github.com/overblog/GraphQLBundle/blob/master/src/Resolver/TypeResolver.php#L69-L73) by `$type = $this->getSolution($alias);` then retry, can you provide the error please?

**Comment by mcg-web** [comment]
seems like you missing this in your config
```diff
overblog_graphql:
    definitions:
        schema:
            query: Query
        mappings:
            auto_discover: false
            types:
                -
-                   type: yaml
+                   type: graphql
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: ~
```

**Comment by enumag** [comment]
Indeed that's it. I'll send a PR to add this to the [GraphQL schema language](https://github.com/overblog/GraphQLBundle/blob/master/docs/definitions/graphql-schema-language.md) page.

Thank you!
