### ISSUE TITLE
Relay Connection, Paginator & Connection builder

### ISSUE THREAD

**Issue by Vincz** [overblog/GraphQLBundle#412]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no

Hey guys,
I have a question regarding the relay connections implementation. 
As describe in the docs, we are able to define connections & edges with additional fields using the `relay-connection` type.
But, tell me if I'm wrong, but the Paginator doesn't handle this custom fields as it use the final classes `Connection` and `Edge`. 
What about adding a little bit of flexibility ? 
We could for example add the ability to define custom classes for the connection and the edge, and callbacks, to populate the connection if needed (after the edges resolved) to add new field to the connection (some calculated fields based on the edges or whatever), and the same way to populate Edges (with custom fields).

So we could add a `ConnectionInterface` and an `EdgeInterface` to ensure the relay fields, and add the ability to pass a custom `ConnectionBuilder` to the Paginator (by default it would be `new ConnectionBuilder()`, so we should use it as an instanciated class and not a static one).

So the api could look like this for example:  

```php

$connectionBuilder = new ConnectionBuilder( 
function($edges, PageInfo $pageInfo) : FriendsConnection {
    $connection = new FriendsConnection($edges, $pageInfo)
    $connection->setAverageAge(calculateAverage($edges));
    return $connection;
},
function(string $cursor, UserFriend $entity):FriendEdge {
   $edge = new FriendEdge($cursor, $entity->getUser());
   $edge->setFriendshipTime($entity->getCreatedAt());
   return $edge;
});

$paginator = new Paginator(function ($offset, $limit) use ($backend) {
    return $backend->getData($offset);
}, true, $connectionBuilder);

$result = $paginator->auto(...);
```

Please, tell me what you think :)

**Comment by calvera** [comment]
:+1:

**Comment by mcg-web** [comment]
Hi @Vincz, I'm totally OK with this enhancement? Do you want to implement it?

**Comment by Vincz** [comment]
Hi @mcg-web !
No problem, I'll take care of it in the coming days :)

**Comment by mcg-web** [comment]
Thank you @Vincz :+1:

**Comment by Vincz** [comment]
Ok, see #413 for the implementation :)
