### ISSUE TITLE
Pagination, response modification...

### ISSUE THREAD

**Issue by tejadong** [overblog/GraphQLBundle#415]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.11

Hello, I do not know how to implement a paging with this bundle, I have read something about relay in the help but I do not get anything clear, the help is very bad I have had thousands of problems to be able to operate this bundle ... Is there any documentation , web page or anything that I can read that is well explained? Another question that arises is this: is there any way to modify the answer when I make a request?

**Comment by mcg-web** [comment]
Hello,

Relay is not a concept of this bundle, we just give a way to implement it here. For more [details see the official documentation](https://facebook.github.io/relay/docs/en/graphql-server-specification.html), also I agree that the bundle documentation need a lot of improvements... You can find an [example using relay connection](https://github.com/mcg-web/graphql-symfony-doctrine-sandbox). 

> Another question that arises is this: is there any way to modify the answer when I make a request?

This is a Symfony bundle so if you want to modify answer you can just use [`kernel.response` event](https://symfony.com/doc/current/reference/events.html#kernel-response).

**Comment by tejadong** [comment]
Thank you a lot :+1:

**Comment by mcg-web** [comment]
Closing this, feel free to continue discussion if needed :+1:
