### ISSUE TITLE
Undefined variable: globalVariables

### ISSUE THREAD

**Issue by arnaud-lb** [overblog/GraphQLBundle#418]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Version/Branch   | 0.11.9

When using a custom global variable, the following error appears:

```
Notice: Undefined variable: globalVariables
```

In the generate type, we can see this code:

```
'resolve' => function ($value, $args, $context, ResolveInfo $info) use ($globalVariable) {
    return $globalVariables->get('faker')->name;
},
```

The generated code uses `$globalVariables` instead of `$globalVariable`

**Comment by mcg-web** [comment]
This part of the bundle is not yet documented, seems you using some hidden features :laughing:, thanks again for the fix!

**Comment by arnaud-lb** [comment]
Thanks for the quick merge :)
