### ISSUE TITLE
Is it possible not to call resolver for a field that is secured?

### ISSUE THREAD

**Issue by ardi-n** [overblog/GraphQLBundle#42]
From what I experience the resolver is called even if a security check for a field does not pass. A field resolver might be expensive to call and I would like to prevent it from being called by setting some access rule.

**Comment by mcg-web** [comment]
No this is not possible because access resolver may need object to know if user has rights. The resolver is not call only in mutation operation. You can create a custom resolver checking rights without having to call the original resolver...

**Comment by ardi-n** [comment]
OK, I get it. What I do now is I inject necessary services to field resolver method and decide there whether it's ok to resolve field's value or not. Thanks.
