### ISSUE TITLE
Cache Permissions issue when clearing

### ISSUE THREAD

**Issue by bastos71** [overblog/GraphQLBundle#421]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | unknown
| RFC?             | no
| Version/Branch   | v0.11.8

It seems that cache files created by the bundle are not well handled when the application try to refresh them, due to rights problems

> [Symfony\Component\Filesystem\Exception\IOException]                                                                                                                                                       
> Failed to remove file "/var/cache/sites/api_advercity/dev/overblog/graphql-bundle/__definitions__/ApiMutationType.php": unlink(/var/cache/sites/api_advercity/dev/overblog/graphql-bundle/__definitions__/ApiMutationType.php): Permission denied. 

The problem occurs on a Vagrant local environment and on a AWS EC2 prodution environment.

Do not hesitate to ask more infos

**Comment by mcg-web** [comment]
That a known error see https://github.com/overblog/GraphQLPhpGenerator/issues/24 for more details. You can [commit generated files](https://github.com/overblog/GraphQLBundle/blob/master/docs/index.md#composer-autoloader-configuration-optional) to don't have to generate them in production environment while waiting for a better fix.

**Comment by bastos71** [comment]
oh thx for link !
I'll take a look about configuring the cache dir and comiting it, but we agree that's not a good thing
Thanks again

**Comment by mcg-web** [comment]
will be soon released
