### ISSUE TITLE
Missing deprecation option for input-object

### ISSUE THREAD

**Issue by Fivedark** [overblog/GraphQLBundle#430]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.11.0

The input-option type should also allow to deprecate some fields like enum and object.

**Comment by mcg-web** [comment]
The [official specs](https://facebook.github.io/graphql/June2018/) don't seems to talk about that. Anyway this should be first implement in [webonyx/graphql-php](https://github.com/webonyx/graphql-php). This bundle is just the Symfony bundle of this lib.

**Comment by mcg-web** [comment]
I'm closing this right now, feel free to continue discussion if needed.

**Comment by Oliboy50** [comment]
we have to wait for https://github.com/graphql/graphql-spec/pull/805

**Comment by jsakars** [comment]
I believe https://github.com/graphql/graphql-spec/pull/805 is done and therefore this should be resolved here as well
