### ISSUE TITLE
webonyx version to 0.13

### ISSUE THREAD

**Issue by apoberez** [overblog/GraphQLBundle#431]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.11

Hello, can we update webonyx/graphql-php version. There is bug in current version https://github.com/webonyx/graphql-php/issues/420

**Comment by mcg-web** [comment]
Hello, we can try but since 0.13 introduce php 7.1 typehint it is not compatible with the bundle 0.11 version. The bump will be certainly done on 0.12-dev (master).

**Comment by mcg-web** [comment]
Fixed in 0.11, will be soon released, thanks again for feedback!
