### ISSUE TITLE
pthreads from the box

### ISSUE THREAD

**Issue by god1dog** [overblog/GraphQLBundle#444]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | x.y.z

Good afternoon, how is it possible to implement multi-threaded **pthreads**?

**Comment by god1dog** [comment]
Opened the question  maybe someone will be interested

**Comment by mcg-web** [comment]
closing this for reason I explains in my previous comment
