### ISSUE TITLE
Add a dockerfile to run tests

### ISSUE THREAD

**Issue by mcg-web** [overblog/GraphQLBundle#447]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.12

**Comment by akomm** [comment]
Can travis run docker?

**Comment by akomm** [comment]
Maybe I can do this. I work a lot with docker. Only not so much with travis. Going to check [this](https://docs.travis-ci.com/user/docker/).

**Comment by akomm** [comment]
Or do you want it for local test only, so you do not have to install all the on your platform?

**Comment by mcg-web** [comment]
This is for local test in a first place.

**Comment by akomm** [comment]
Do you want it run different php versions like on travis or a single one? (I usually run the most recent for local test, as the other is covered by travis and managing all the versions is time consuming).

**Comment by mcg-web** [comment]
The most recent for local tests are sufficient
