### ISSUE TITLE
Resolver autowiring not work if different folder structure

### ISSUE THREAD

**Issue by maxtorchel** [overblog/GraphQLBundle#448]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.11.11, dev-master

i want to realize business logic folder structure (Core, Products etc), and for this i use following service config:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Overblog\GraphQLBundle\Definition\Resolver\ResolverInterface:
            public: true
            tags: ['overblog_graphql.resolver']
        Overblog\GraphQLBundle\Definition\Resolver\MutationInterface:
            public: true
            tags: ['overblog_graphql.mutation']

    App\:
        resource: '../src/*'
        exclude: ['../src/{Kernel.php}',
            '../src/*/{DependencyInjection,Migrations,Entity,Tests,Exceptions,Events,Types}']

login resolver:

```
namespace App\Core\GraphQL\Login;

use Overblog\GraphQLBundle\Definition\Resolver\ResolverInterface;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;

class LoginResolver implements ResolverInterface {
  public function login(){
     return true;
  }
}
```

and in loginQuery `@=resolver("App\\Core\\GraphQL\\Login\\LoginResolver::login", [args["login"]])`.

But i got error `Unknown resolver with alias "App\Core\GraphQL\Login\LoginResolver::login" (verified service tag)`. I try last stable version and master branch with symfony 4.2 but no luck.
What i doing wrong?

**Comment by mcg-web** [comment]
Can you try this command line:
```
bin/console graphql:debug --category=resolver
```

**Comment by maxtorchel** [comment]
```
GraphQL Resolvers Services
==========================

 ------------------------------------------------------------------------------ -------------------------------- 
  solution id                                                                    aliases                         
 ------------------------------------------------------------------------------ -------------------------------- 
  App\Core\GraphQL\Login\LoginResolver                                                                           
  App\Core\GraphQL\User\UserResolver                                                                             
  Overblog\GraphQLBundle\GraphQL\Relay\Mutation\MutationFieldResolver            relay_mutation_field            
  Overblog\GraphQLBundle\GraphQL\Relay\Node\GlobalIdFieldResolver                relay_globalid_field            
  Overblog\GraphQLBundle\GraphQL\Relay\Node\NodeFieldResolver                    relay_node_field                
  Overblog\GraphQLBundle\GraphQL\Relay\Node\PluralIdentifyingRootFieldResolver   relay_plural_identifying_field  
 ------------------------------------------------------------------------------ -------------------------------- 

```
If i use AliasedInterfase all works fine.

**Comment by mcg-web** [comment]
if just implementing AliasedInterface returning an empty array for getAliases it works?

**Comment by maxtorchel** [comment]
no

**Comment by mcg-web** [comment]
This seems to be a bug must give it a try myself to fix it, thank you for feedback

**Comment by akomm** [comment]
@maxtorchel does adding `\\` fix it?

`@=resolver("\\App\\Core\\GraphQL\\Login\\LoginResolver::login", [args["login"]])`

**Comment by maxtorchel** [comment]
no

**Comment by akerbel** [comment]
I got the same problem. My project already has a classic frontend and I tried to attach GraphQL. Everything works only if it is full covered by aliases.

```
  App\GraphQL\Resolver\ProjectResolver:
        arguments:
            $em: '@doctrine.orm.entity_manager'
        tags:
            - { name: overblog_graphql.resolver, method: "resolve", alias: 'project_resolver' }
            - { name: overblog_graphql.resolver, alias: 'project_invoker' }
```

**Comment by murtukov** [comment]
@maxtorchel Still have this issue? How about v0.12?

**Comment by mcg-web** [comment]
This issue seems to be inactive for quite some time now, so I've closed it. If you feel this issue deserves some attention feel free to reopen it.
