### ISSUE TITLE
custom accessor

### ISSUE THREAD

**Issue by ddlzz** [overblog/GraphQLBundle#462]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.11.9

hi there! is it possible to use some kind of custom accessors for entity fields?

I mean it would be great to have something like

```
class ProductCaterogy
{
    /**
     * @GraphQLAccessor("getActiveProducts")
     */
    private $products;
    
    public function getActiveProducts()
    {
    return array_map(...)
    }
}
```

and then
```
{
    productCategories {
    products {
      title
    }
  }
}
```
would give us the result of a custom getter.

**Comment by mcg-web** [comment]
ping @Vincz this seem to already be include in annotations branch, I'm I right?

**Comment by Vincz** [comment]
Hey ! Yes, with annotation, you can use the `@GQL\Field` annotation on properties or on methods. 
See https://github.com/overblog/GraphQLBundle/blob/annotations/docs/annotations/annotations-reference.md#field

**Comment by ddlzz** [comment]
thanks guys!
