### ISSUE TITLE
How to configure bundle for accepting only POST requests?

### ISSUE THREAD

**Issue by sanan-tech** [overblog/GraphQLBundle#464]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.11.11

Hi:) I need configure bundle for accepting only HTTP POST requests. How to make it?

**Comment by osavchenko** [comment]
You can specify it in your routing file (just add `methods: POST` to the GraphQL endpoint)

**Comment by sanan-tech** [comment]
thanks!
