### ISSUE TITLE
Error formatting

### ISSUE THREAD

**Issue by osavchenko** [overblog/GraphQLBundle#466]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Version/Branch   | 0.11.12

In [documentation Error formatting](https://github.com/overblog/GraphQLBundle/blob/0.11/docs/events/index.md#error-formatting) result looks like:
```
{
  "data": null,
  "errors": [
    {
      "code": 123,
      "category": "internal",
      "message": "Internal server Error"
    }
  ]
}
```

but in latest update it have different format:
```
{
  "data": null,
  "errors": [
    {
      "code": 123,
      "extensions": {
        "category": "internal",
      }
      "message": "Internal server Error"
    }
  ]
}
```

Could you advice how to avoid `extensions` and continue use previous format?

**Comment by mcg-web** [comment]
This change is coming from the latest graphQL specs, if you do not want to use it right now, just lock webonyx/graphql-php to 0.12.* version in your composer file

**Comment by osavchenko** [comment]
Thank you for the information!
