### ISSUE TITLE
use GraphQuery without HTTP

### ISSUE THREAD

**Issue by hjanuschka** [overblog/GraphQLBundle#470]
is there a way that one can use a Query and get a json response without HTTP?

like  (pseudo)

```php

$query = '{
  post(id: 10407) {
      title,
      pretitle,
      id
  }
}';

$re = $this->service->query($query);
//$re ---> is the response json
```

so we could internally use the graph api a bit better?

**Comment by mcg-web** [comment]
You can use service `overblog_graphql.request_executor` it is public.
`$requestExecutor->execute($schemaName, $requestParams, $rootValue);` where `$schemaName` can be null, `$requestParams = ['query' => '...', 'variables' => '...', 'operationName' => '...' ]`, `$rootValue` can also be null

**Comment by hjanuschka** [comment]
@mcg-web  thats nice, going to give it a try, many thx!

**Comment by mcg-web** [comment]
Closing this, feel free to continue discussion here if needed.
