### ISSUE TITLE
Caching issues >`var/graphql` should be within the container folder

### ISSUE THREAD

**Issue by ruudk** [overblog/GraphQLBundle#480]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | v0.11.12

We are actively using GraphQLBundle in 2 big projects. The first project is using it already using it since the beginning of this amazing bundle. The other project just recently started using it.

Both projects now have the same issues: `internal server errors: failed to open var/graphql/QueryType.php`. Trying `bin/console cache:clear` sometimes solves it, sometimes not. Manually clearing the `var/cache/*` sometimes solves it, sometimes not.

Somehow we believe that this issues kicks in when 2 processes try to re-create the cache. This can easily happen when you have a frontend that retries the API in the background. 

I think the issue here is that this bundle stores its cache in 1 shared folder `var/graphql` instead of `var/cache/dev/ContainerId/graphql`. Symfony solves this problem by always creating a new folder, and then replacing the old with the new one. 

Are more people experiencing these issues?

**Comment by mcg-web** [comment]
We have the same issue when using it dev  env without cache with a js client. The bundle store the generated files in `var/cache/{env}/overblog/graphql-bundle` dir. We can move this in `var/cache/{env}/{ContainerId}/overblog/graphql-bundle` if this can solve this issue.

**Comment by ruudk** [comment]
I think it makes a lot of sense to connect it to the compiled container id. When the container is rebuilt, it probably means that the configuration was changed. That should also trigger the GraphQL bundle to re-update. 

Would it be hard to change its location to the containerId?

**Comment by mcg-web** [comment]
I search to find how to locate cache in the same dir of the container build but this part don't seem to be documented.

**Comment by akomm** [comment]
Actually, I am using version `dev-master#d273a2efd2d9b7385cc0e95f8ed1e473aedf698c`, which has its definitions namespaced by `containerId`. However it also fails to load Types. Less random. It seem to almost always fail, sometimes randomly it does not. Had no time checking why that is.

I checked bundle extension config and found a way around it, which I leave that way as it seems better than the default anyway:
```yaml
overblog_graphql:
  definitions:
    class_namespace: 'App\GraphQL\Definitions'
    cache_dir: '%kernel.project_dir%/src/GraphQL/__generated__/Definitions'
    cache_dir_permissions: 0750
    use_classloader_listener: false
```
And added composer psr4 autoload entry:
```json
"App\\GraphQL\\Definitions\\": "src/App/GraphQL/__generated__/Definitions/"
```

However the default behavior seem to have some sort of issue. Pull-wise I do not see how this should have changed until the current master, here is the commit I use:

https://github.com/overblog/GraphQLBundle/commit/d273a2efd2d9b7385cc0e95f8ed1e473aedf698c

**Comment by akomm** [comment]
I have to admit I was confused by something, the generated output is not inside the containerId directory, it was just the service using them.
