### ISSUE TITLE
Flex unconfiguration

### ISSUE THREAD

**Issue by akomm** [overblog/GraphQLBundle#492]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.11, 0.12-dev

@mcg-web can this be triggered by something in the way how the recipe is defined:

https://github.com/symfony/flex/issues/497

I have to add, it was unconfigured on an composer update with version 0.11 too after I wrote the other issue, so has nothing to do with using a dev version.

I currently assume its a flex thing, however would like to exclude something in the recipe itself triggers it (which still might be a bug in flex, but maybe BC fixable from recipe).

**Comment by mcg-web** [comment]
I'm closing this issue in favor of #465

**Comment by akomm** [comment]
Oh, could not have guessed it by the title :)
