### ISSUE TITLE
Add @GQL\Access support on @GQL\Provider

### ISSUE THREAD

**Issue by Vincz** [overblog/GraphQLBundle#506]
| Q                | A
| ---------------- | -----
| Feature request? | yes

It would be great if `@GQL\Provider` would support the `@GQL\Access` & `@GQL\Public` annotations.
The `@GQL\Access` defined on the class provider would be used as the default access for queries and mutations defined in the Provider.

**Comment by mcg-web** [comment]
Fixed by #507, thank you!
