### ISSUE TITLE
Add the ExecutorArgumentsEvent as property to the ExecutorResultEvent

### ISSUE THREAD

**Issue by Vincz** [overblog/GraphQLBundle#513]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Hey @mcg-web ! As title said, I'd like to add the `ExecutorArgumentsEvent`  in the `ExecutorResultEvent` of the executor `Overblog\GraphQLBundle\Request\Executor`.
What do you think? I need a way to know what was the operation, variables, etc... and what was the result of an executed function. It can be useful for logging and others use cases. Mine is the ability to know the operation and result in order to publish it in a redis pub/sub and handle it in a nodejs subscription server.
If it's ok for you, I will write a PR (there is no BC break, just an additional property on the `ExecutorResultEvent`.

**Comment by mcg-web** [comment]
Hi @Vincz this look good to me. This really answer to a need.

**Comment by Vincz** [comment]
I made it work, but I have a small issue that I don't really know how to solve.
Initially, I  wanted to get the query being executed and the corresponding result. 
It all append in the `Overblog\GraphQLBundle\Request\Executor`. 
My problem is that I wanted the parsed `requestString` but I get the raw one. 
If I parse it myself, it means it would be parsed twice (not good for performances). 
But at the moment, I didn't find a way as the request string is parsed deep in the base GraphQL lib (https://github.com/webonyx/graphql-php/blob/c45fa1a4b189c4356b21eed8a364165b8214eeb3/src/GraphQL.php#L131).
I still think it could be really valuable to be able to get "what append with a query".

**Comment by akomm** [comment]
@Vincz do you want the AST?

**Comment by akomm** [comment]
@Vincz the only trace back to the AST we have is in the `ResolveInfo`. The rest is all in webonyx-php code. 

`ResolveInfo` has operation property. Its also AST (`OperationDefinitionNode`) processed from the `DocumentNode` (the source you linked). 

The point where its mapped and handled by overblog_graphql code is inside the closure returned from `\Overblog\GraphQLBundle\Definition\ArgumentFactory::wrapResolverArgs`, which is basically a resolver wrapped, so at the end of the gay webonyx only exposes it to resolver functions.

I think it needs a feature on webonyx-php itself to cleanly get the AST/ResolveInfo outside of resolver functions.

**Comment by Vincz** [comment]
Implemented in https://github.com/overblog/GraphQLBundle/pull/696
