### ISSUE TITLE
How can i test the queries?

### ISSUE THREAD

**Issue by allanzi** [overblog/GraphQLBundle#518]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | ^0.11.12

I'm using the bundle and now i need test my application, but i can't think how to mock or something.

Thanks all.

**Comment by mcg-web** [comment]
Functional tests are the best to test an API ([here an example of how this can be done](https://github.com/mcg-web/graphql-symfony-doctrine-sandbox/blob/master/tests/AppBundle/Functional/StarWarsQueryTest.php)) but resolver and mutation can be unit tested like any other service if needed.

**Comment by mcg-web** [comment]
Feel free to continue discussion here if needed.
