### ISSUE TITLE
Problem when using XDebug during a query

### ISSUE THREAD

**Issue by felyx** [overblog/GraphQLBundle#520]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes/no
| RFC?             | no
| Version/Branch   | 0.11.13

When I try to run a query while using XDebug I get the following error and I could not fix it so far:

> Symfony\Component\Finder\Exception\DirectoryNotFoundException: The "vendor\symfony\framework-bundle/GraphQL" directory does not exist.

Here are my config and the types and resolver: https://gist.github.com/felyx/b2638d147170133efbf8e769849a8c7d

**Comment by mcg-web** [comment]
try replacing  [these lines](https://gist.github.com/felyx/b2638d147170133efbf8e769849a8c7d#file-config_graphql-yaml-L15-L16) by 
```yaml
        App\GraphQL\:
            resource: ../src/GraphQL
```
then
`bin/console c:c` and retry please

**Comment by felyx** [comment]
I tried that, I even tried to remove that graphql config file altogether and then manually deleting the cache dir also to avoid not properly clearing the cache but the problem still remains the same.

**Comment by felyx** [comment]
I have also tried this way:

> App\GraphQL\:
            resource: '%kernel.project_dir%/src/GraphQL'

The error is the same still.

**Comment by felyx** [comment]
I also tried a completely clean install just to see if it is an issue with the previous install. I only installed symfony skeleton, doctrine orm pack, and the overblog graphql bundle. I almost left everything as it is in the default install except setting up the database connection and the type definitions and resolver. I was able to reproduce the bug on the clean install as well.

> ...SymfonySkeleton\vendor\symfony\framework-bundle/GraphQL" directory does not exist. in ...SymfonySkeleton\vendor\symfony\finder\Finder.php:601

**Comment by murtukov** [comment]
@felyx Did you solve your issue?

**Comment by felyx** [comment]
@murtukov Nope, I am on the Symfony slack overblog channel and talked to @mcg-web about it, he told me he is going to look into the issue this week so I am hoping he will be able to find the issue because we really miss the ability to use XDebug.

**Comment by murtukov** [comment]
@felyx I am using XDebug and have no problem with it. I don't think it has something to do with this bundle. You said that you have this issue even with clean install, right? Could you publish this clean project somewhere, so that i could install it and check my myself?

**Comment by felyx** [comment]
@murtukov I will invite you shortly to the repo I shared with @mcg-web which has that skeleton app I mentioned, he tried it and he also said that it must be something about our configuration, not the bundle itself.

**Comment by murtukov** [comment]
@felyx Installed your repository and it work perfectly.

Here is a screenshot with activated XDebug:
![image](https://user-images.githubusercontent.com/19292777/61484395-2ceaf280-a99f-11e9-8f6c-cce94a2c8c2e.png)

Hope there is no private data on the screenshot. If so, let me know.

I think you have an issues with your Composer or Xdebug config.

**Comment by felyx** [comment]
@murtukov Interesting. With Laravel projects, it works fine so I would not think it is something related to the XDebug config, composer might be tho no idea why or what or it could be Visual Studio Code (we use vscode to dev) or something about access rights... Again, since everything works fine in non-symfony projects I did not think it could be anything else. I will check again tomorrow when I am back at work. Thank you for the effort you made trying to help me!

**Comment by murtukov** [comment]
@felyx Try to provide more information, like logs, your OS, your XDebug configs for your project and more detailed exception message (trace etc.)

Try to clear the composer cache.

**Comment by felyx** [comment]
@murtukov Tomorrow I will check it again and provide more detailed information about the issue.

**Comment by felyx** [comment]
So @murtukov 

OS: Windows 10 x64
Visual Studio Code: latest
PHP: v7.3.3
XDebug conf and version:
[XDebug]
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
zend_extension=php_xdebug-2.7.1-7.3-vc15-nts-x86_64.dll

When I first try to run the debugger I get the following Exception:
`var\cache\dev\pools\0flXA1BYf+\C\R\iI7euN4OxW-zn9IcjAug): failed to open stream: No such file or directory`

Then I delete the var\cache dir and this exception doesn't show (until I run the app without XDebug again, after then the same happens) but I get an other exception:
`Exception has occurred.
Symfony\Component\Finder\Exception\DirectoryNotFoundException: The "vendor\symfony\framework-bundle/GraphQL" directory does not exist.`

And this is the one I could not do anything about.

**Comment by felyx** [comment]
@murtukov Well I took the time to test it in PHPStorm as well and I do not get those exceptions in there only when I debug with Visual Studio Code. :/

**Comment by murtukov** [comment]
@felyx Hmm, maybe a clean install of your VSC would help. You can test the fresh install in the [Windows Sandbox](https://techcommunity.microsoft.com/t5/Windows-Kernel-Internals/Windows-Sandbox/ba-p/301849) or create a new windows profile and test it there. 

I am closing this issue as it's not relevant to the bundle.

**Comment by juangcCM** [comment]
@hblaise could you update a bit about this? I am also struggling to use xdebug here.

**Comment by juangcCM** [comment]
I managed to make it work. In my case the mapping was wrong in PHPStorm -> Settings/Servers.
I had a few folders excluded so the mapping was totally unaccurate.
