### ISSUE TITLE
[Annotation] Add option to @Provider to attach to different types

### ISSUE THREAD

**Issue by akomm** [overblog/GraphQLBundle#526]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | ^0.12

Currently you can only provide fields to root types via `@Provider` and `@Mutation`/`@Query` on those root types. AFAIK this is also limited to the [default schema root types](https://github.com/overblog/GraphQLBundle/blob/v0.12.0/docs/annotations/annotations-reference.md#query).

I realized this is also needed for non root types, when you have for example two fields connecting something and this logic requires some different services, I have currently to create a type (service) with two dependencies for different purposes. 

There are maybe different ways of doing it. One could be:
Instead of `@Query` and `@Mutation`, give `@Provider` an option like `type=Query`, which would make the annotated field, etc. being "injected" into the type `Query`. This would also allow it to work with any type and independent of schema (single, multi).

**Comment by Vincz** [comment]
Hi @akomm 
Actually, their is an option `targetType` on `@Query` to target a different type for queries.
See [Query annotation](https://github.com/overblog/GraphQLBundle/blob/master/docs/annotations/annotations-reference.md#query)

**Comment by akomm** [comment]
@Vincz You are right, the I currently have the exact same page open, the description initially confused it as it states it does use the Query from definitions config. :)

**Comment by Vincz** [comment]
The idea of `@Provider` was to be able to tell the parser that this specific class contains queries and/or mutations and be able to "group" them (with a prefix, or with `@Access`). I don't know if I picked the best option to do so. 
But we could add a `queriesTarget` on the `@Provider` to automatically add the `targetType` on queries contained in the Provider. I don't know...

**Comment by akomm** [comment]
It is still a bit different to my proposal, as it is then on per-field base not `@Provider` but might be enough, can not tell yet what is better.

I think the docs should then be something like:
`By default, the resulting field is added to the main Query type (define in configuration at key overblog_graphql.definitions.schema.query)`
instead of:
`The resulting field is added to the main Mutation type (define in configuration at key overblog_graphql.definitions.schema.query).`

**Comment by akomm** [comment]
Oh and missing it on Mutation too. Going to add it there too. :)

**Comment by Vincz** [comment]
That is what I was about to say ^^

**Comment by akomm** [comment]
So was almost about to close this with the doc fix, but it looks like its not yet fully supported as mutation does not have it. However I think currently I can live with this, because AFAIK I will only need this on types, not input types. And types are covered via `@Query`. (Also, I did not yet dig much into the details, but I think its also only semantic like the mutation and resolver functions in expressions?)

The question is, close or leave it to evaluate if it makes sense to change/generalize something on it?

**Comment by akomm** [comment]
@Vincz its not exactly the proposed feature and mutation does have the field, but I mostly need this on query types, so it should be no problem. I close it and should there be any issue I did not notice yet, I reopen it.

**Comment by snaksa** [comment]
@Vincz @akomm Hello, is there any reason why there is no targetType option for the Mutation case? For example I want to implement two different schema types - one with access control and one without. 
This definition is exactly what I need but I can have only one mutation type because I can't set any mutations in the **bar** one and an error is triggered. All mutations that I add with annotations are being assigned to the default mutation.

```yaml
schema:
   default:
      query: Query
      mutation: Mutation
   bar:
      query: AuthorizedQuery
      mutation: AuthorizedMutation
```
with access control
```yaml
access_control:
         - { path: ^/graphql/bar, roles: ROLE_USER }
```

I get  the following error:

> The path "overblog_graphql_types.AuthorizedMutation._object_config.fields" should have at least 1 element(s) defined.

**Comment by Vincz** [comment]
@snaksa Hi ! You are right, I didn't think about multiple schemas when I implemented this. So, it would also make sense to handle targetType for mutations too. Feel free to PR, or if you can't, I'll try to check this by the end of the week.

**Comment by snaksa** [comment]
Hi! As we discussed I added a PR that implements this :)

**Comment by Vincz** [comment]
Hey @snaksa ! Thank you for this PR ! It's a really good start. I did a little review and hope it is clear otherwise I'll be glad to help.

**Comment by Vincz** [comment]
Done in #710 & #725
