### ISSUE TITLE
The queried fields

### ISSUE THREAD

**Issue by kejianxin** [overblog/GraphQLBundle#552]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Will The queried fields have the option to be retrieved dynamically from the database?

**Comment by ooflorent** [comment]
You can implement this with a compiler pass or a pre-build step I guess.

**Comment by mcg-web** [comment]
This issue seems to be inactive for quite some time now, so I've closed it. If you feel this issue deserves some attention feel free to continue it here.
