### ISSUE TITLE
Queries details in Profiler

### ISSUE THREAD

**Issue by mathroc** [overblog/GraphQLBundle#555]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.12

Hi, 

it would be really helpful to add a section in the WebProfiler for GraphQL, it should probably be similar to the Doctrine section, what I would be mainly interested in:

* listing all graphql queries handled (with individual times and cumulated time)
* see the raw graphql query
* see the graphql query variables
* see the graphql query result *and/or* run the query again
* see errors thrown when resolving the query

nice to have:

* pretty format for graphql queries
* open in graphiql
* display more debug from graphql extensions results

**Comment by mcg-web** [comment]
Hi, this a feature I wanted to add since the starting of the project but sadly never get the time to implement it.

**Comment by Vincz** [comment]
It would be really great. A really nice addition would be the ability to display the executed graphql queries/mutations names in the HTTP queries list (on the `/search/results?limit=10` page) cause it's sometimes hard to find the HTTP query you are looking for as they are all matching the same endpoint url.

@mathroc : Are you gonna work on it ?

**Comment by mathroc** [comment]
@Vincz I'd love to but I won't have the time for that in the coming weeks :/ it's on my todo list so maybe sometime :sweat_smile:  I'll tell it here if I start working on it

**Comment by murtukov** [comment]
@Vincz I guess I'm gonna work on it

**Comment by Vincz** [comment]
Hey @murtukov ! Any update about this?
If you didn't start, I think I'll have a couple of hours to dedicate to this feature this week.

**Comment by murtukov** [comment]
@Vincz Hi. No, I didn't start yet. I am currently working on other features and it will take a huge amount of time. You can work on the Profiler feature if you want.

**Comment by Vincz** [comment]
Ok mate :) Good luck with your stuff !
