### ISSUE TITLE
Can the generated schema be modified after loading?

### ISSUE THREAD

**Issue by Vassyli** [overblog/GraphQLBundle#57]
Same background as in #56 - i'd like to provide a way to extend the schema. Is there a possibility to change the schema after it's being read by the graphql bundle?

**Comment by ooflorent** [comment]
No it's not possible. Can you describe your use-case?

**Comment by Vassyli** [comment]
We are currently writing a 2 layered browser game engine - consisting of a core and something we call a crate. Our crate is wrapping the core library and providing a graphql api for actually playing the game. The core does only contain very basic functions, everything else needs to be added by modules that can extend both core and crate.

Our issue lies for example if a module wants to provide an additional graphql query (for, lets say, loading comments). Here, a possibility to extend the graphql query type is important to us, so the module can provide this additional api endpoint. The same is of course true for mutation endpoints.

**Comment by mcg-web** [comment]
Multiple endpoint with different schema will be implement in a coming feature.

**Comment by mcg-web** [comment]
thanks to #65 it is now possible to have many schema in the same project
