### ISSUE TITLE
Extract the logic to map the exceptions to GraphQL exceptions into a factory

### ISSUE THREAD

**Issue by ste93cry** [overblog/GraphQLBundle#583]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.13

In the application I'm developing I have some classes to retrieve the data from a certain datasource that can possibly throw some exceptions (e.g. `EntityNotFoundException`). Since  GraphQL is just one way to "fetch" this data, these exceptions should not and don't know anything about it, nor the base `UserError` class (or `ClientAware` interface). I would like to remap those exceptions to the ones that are appropriate for GraphQL and I was looking at the `errors_handler.exceptions` configuration option. However, in the `OverblogGraphQLExtension` class the mapping is hardcoded between the list of exceptions and the `UserError` and `UserWarning` classes, leaving no way to the user to wrap those exceptions into a custom GraphQL error class or leaving the possibility for that base class to be constructed with custom arguments as the instantiation is hardcoded too. I was thinking of extending the `ErrorHandler` with some custom logic, however I found out a few problems too there:

- The class does not implements any interface, so I cannot swap the service easily
- The class has most of the methods and properties `private`, which makes impossible to extend its behavior without copy-pasting almost all logic inside (this is what I did for the moment)

It turns out that the most flexible way would be to introduce an interface for the error handler and inject a factory that is able to create the instances of the exceptions instead of the "static" map of exceptions. Depending on whether you are willing to break BC or not this feature may be implemented in a BC-compatible way or not. If you agree, I would like to work on a PR with the needed changes

**Comment by mcg-web** [comment]
The proposal seem to be a good enhancement so your PR would be welcome :+1:

**Comment by ste93cry** [comment]
Would you like me to write the feature in a way that does not break BC or not? Depending on this the implementation must change, so it's a detail that I have to know before starting to put effort on coding. Obviously not thinking about compatibility with older versions means that I have more freedom on how to code the feature

**Comment by mcg-web** [comment]
I think you should forget the current behavior, I'll work on compatibility after if needed.

**Comment by ste93cry** [comment]
I'm closing this because the related PR has been merged. Thank you for being so fast in accepting the contribution
