### ISSUE TITLE
Auto register the resolver maps using service tagging

### ISSUE THREAD

**Issue by ste93cry** [overblog/GraphQLBundle#592]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.13

I was thinking about the reason why the resolver maps are registered manually in the configuration instead of being tagged services that can be injected by the service container directly into the `TypeDecoratorListener` service. The only reason I can think of is that the order in which they are registered can matters, but this can be easily solved using a solution similar to the one of the listeners that can configure their priority. I would be happy to provide a PR that automatically registers the maps. I would also stop supporting the `overblog_graphql.definitions.schema.resolver_maps` option, but this would be a BC so maybe we can just deprecate it. WDYT?

**Comment by mcg-web** [comment]
The bundle supports many schema so resolver map auto registration should also make this configurable (using a service attribute tag?). We can deprecate the option in this version and remove it in the next one. Do you want to work on a PR?

**Comment by ste93cry** [comment]
>Do you want to work on a PR?

Yes, I will try to get something up as soon as possible
