### ISSUE TITLE
Validation results are ignored

### ISSUE THREAD

**Issue by kix** [overblog/GraphQLBundle#616]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | looks like so
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.12.3+

So, I've added an input object that is properly annotated and has validation rules attached to it:

```php
/**
 * @GQL\Input()
 */
class CreateTagInput
{
    /**
     * @GQL\Field(type="Int!")
     *
     * @var int
     */
    private $tagId;

    /**
     * @GQL\Field(type="String!")
     * @Assert\NotBlank()
     * @Assert\Length(min=3, max=255)
     *
     * @var string
     */
    private $slug;

     // etc ...
}
```

I have it set up in my mutation as well. When I pass valid arguments with the mutation, everything works as expected. But once I pass in invalid values, and the validator kicks in, all I get is this exception:

```
{
  "errors": [
    {
      "message": "An unknown error occurred.",
      "extensions": {
        "category": "user"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createTag"
      ]
...
```

Looks like `\Overblog\GraphQLBundle\EventListener\ValidationErrorsListener` is intended to handle errors and output them, but the intention is unfinished. Should I implement my own listener that would return and format errors for me, or was this supposed to be a built-in feature of this bundle?

**Comment by akomm** [comment]
I think the Listener is dead code. IIRC the errors should be handled by [this](https://github.com/overblog/GraphQLBundle/blob/master/docs/error-handling/index.md) feature already.

I think your issue is, that a non validation exception is thrown, therefore you do not see validation errors. 

Does your response not include the exception/trace and message?

**Comment by kix** [comment]
Turns out I was not seeing the actual validation error due to the fact that there was a trace for the exception being thrown, also included in the response.

**Comment by murtukov** [comment]
@kix So you just didn't scroll down the response content? 😄 

P. S. Traces won't be included in prod environment.
