### ISSUE TITLE
How send and process context?

### ISSUE THREAD

**Issue by des1roer** [overblog/GraphQLBundle#617]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

How send and process context?

**Comment by murtukov** [comment]
@des1roer 

Your message makes no sense.

**Comment by mcg-web** [comment]
@des1roer can you provide some use case or examples of what you trying to do please?

**Comment by des1roer** [comment]
in graphql exist context

https://graphql-modules.com/docs/introduction/context

i can use it?

**Comment by murtukov** [comment]
@des1roer 

Yes you can use it:
```
resolve: "@=resolver('myResolver', [args, context])"

Russian: Тебе нужно получить доступ к контексту в твоем резолвере? Просто передавай в твоих конфигах переменную **context** в резолвер, как показано в примере выше. Я там передал в резолвер две переменные **args** и **context**. Передавать можно в любом порядке. твой резолвер затем будет выглядет примерно так:

```php
public function myResolver($args, $context) {
    // ...
}
```

**Comment by des1roer** [comment]
russian;
у меня в yaml

         affiliateClicksAndCommission:
                type: "AffiliateClicksAndCommission!"
                resolve: "@=resolver('affiliateClicksAndCommission', [args['startDate'], args['endDate'], args['retailerReference']])"
                args:
                    startDate:
                        type: "DateTimeImmutable!"
                        description: "Select from datetime (time format must be like '2019-10-01T00:00:00+00:00')"
                    endDate:
                        type: "DateTimeImmutable!"
                        description: "Select to datetime (time format must be like '2019-30-01T00:00:00+00:00')"
                    retailerReference:
                        type: "String!"
                        description: "Retailer reference like 'bookexperiencedays.com', 'bookF1TeamMcLaren'"

в резолвере

    public static function getAliases(): array
    {
        return [
            'resolveItem' => 'affiliateClicksAndCommission',
        ];
    }

    public function resolveItem(
        DateTimeImmutable $startDate,
        DateTimeImmutable $endDate,
        string $retailerReference
    ): AffiliateClicksAndCommission {

не очень понимаю. т.е. контекст также как параметр передавать?
и как тогда запрос строится? 

сейчас

		{
		  affiliateClicksAndCommission(
		    startDate: "2019-10-01T00:00:00+00:00", 
		    endDate: "2019-30-01T00:00:00+00:00",
		    retailerReference: "some"
		  ) {
		    clicks {
		      description
		      quantity
		      value
		      commission
		    }  
		  }
		}

**Comment by murtukov** [comment]
@des1roer 

**Короткий ответ**: твой запрос никак не изменится.

**Длинный ответ:**
То, как ты определяешь аргументы в своем запросе, никак не связано с тем, как ты передаешь параметры в твой резолвер. Ты не должен передавать параметры в резолвер в том же порядке, что и в твоем запросе. 

Другими словами это:
```php
public function resolveItem(
    DateTimeImmutable $startDate,
    DateTimeImmutable $endDate,
    string $retailerReference
): AffiliateClicksAndCommission {
   // ...
}
```
никак не  связано с этим:
```graphql
{
  affiliateClicksAndCommission(
    startDate: "2019-10-01T00:00:00+00:00", 
    endDate: "2019-30-01T00:00:00+00:00",
    retailerReference: "some"
) { 
  # ...
}
```

**Все** аргументы твоего **запроса**, всегда сохраняются в переменную `args`. А как ты передаешь `args` в твой резолвер уже зависит полностью от тебя. Ты в своем случае отправил каждый из трёх аргументов по отдельности:
```php
[args['startDate'], args['endDate'], args['retailerReference']]
```
А значит твой резолвер должен ожидать 3 аргумента в той же последовательности. Если ты добавишь еще один аргумент в твой конфиг (context), то это будет выглядеть вот так
```
[args['startDate'], args['endDate'], args['retailerReference'], context]
```
следовательно и твой php резолвер будет принимать на 1 аргумент больше:
```php
public function resolveItem(
    DateTimeImmutable $startDate,
    DateTimeImmutable $endDate,
    string $retailerReference,
    $context
): AffiliateClicksAndCommission {
   // ...
}
```

Важный момент. Ты можешь отправишь все аргументы разом, нет никакой необходимости отправлять их в резолвер по отдельности. Пример:
```
[args, context]
```
а в резолвере уже можешь извлекать нужные тебе аргументы запроса:
```php
public function resolveItem($args, $context): AffiliateClicksAndCommission {
   $startDate = $args['startDate'];
   $nedDate = $args['endDate'];
   $retailerReference = $args['retailerReference'];

   // ...
}
```

**Comment by des1roer** [comment]
![image](https://user-images.githubusercontent.com/10970793/69424097-98780e80-0d49-11ea-903e-732ce0eaf935.png)

      dd($args, $context);

оно вроде как все в аргументы уходит

**Comment by murtukov** [comment]
@des1roer Я вроде понятно объяснил, что ты не должен менять свой запрос. Зачем ты добавил аргумент с именем context? Контекст - это не аргумент, ты его не создаешь сам. Он создается системой и содержит всякую служебную информацию.

**Comment by des1roer** [comment]
а сам я не могу записать в контекст?

**Comment by murtukov** [comment]
@des1roer Не только можешь, но и должен, потому что контекст для этого и предназначен. Он изначально пустой, но записывать в него ты должен внутри резолвера, чтобы потом получить доступ к записанным данным в другом резолвере.

Контекст нужен, чтобы иметь какие-то общие данные между всеми резолверами.

```php
public function firstResolver($context) {
    $context->offsetSet('firstName', 'Alex'); // записываешь данные
    $context->offsetSet('lastName', 'Kowalski');
}

public function secondResolver() {
    $firstName = $context->offsetGet('firstName');
    $lastName = $context->offsetGet('lastName');
}
```

P.S. Не обязательно использовать методы offsetSet и offsetGet, можно записывать и считывать данные, как с обычным массивом:

```php
$context['firstName'] = "Alex";
```

Я закрываю этот issue, потому что он не имеет ничего общего с этим бандлом. Эти вопросы относятся к GraphQL в целом.
