### ISSUE TITLE
how to config a  fragment type??

### ISSUE THREAD

**Issue by lucky-cls** [overblog/GraphQLBundle#618]
|

**Comment by murtukov** [comment]
@lucky-cls Fragment is a frontend thing, so you configure it in the frontend, not in the backend. In other words fragments has nothing to do with this bundle

**Comment by lucky-cls** [comment]
> @lucky-cls Fragment is a frontend thing, so you configure it in the frontend, not in the backend. In other words fragments has nothing to do with this bundle

Thank you, I just realized this.
