### ISSUE TITLE
Symfony 5

### ISSUE THREAD

**Issue by Vincz** [overblog/GraphQLBundle#620]
It would be great to publish a new version with Symfony 5.0 compatibility

**Comment by mcg-web** [comment]
Since 0.1 is the most used version of the bundle I'll also push a patch to support Symfony 5.0

**Comment by mcg-web** [comment]
Done in `v0.11.17` and `v0.12.4`!

**Comment by Vincz** [comment]
You're the best @mcg-web ! 
Thank you ! ❤️
