### ISSUE TITLE
Use overblog/graphql-php-generator as dependency

### ISSUE THREAD

**Issue by enumag** [overblog/GraphQLBundle#628]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | v0.12.5

I want to use the `overblog/graphql-php-generator` without this bundle but noticed something strange - it refused to install with Webonyx 0.13 even though I was already using that version with the bundle. After some digging I noticed that somehow this package is not installed as a normal composer dependency but instead embedded directly into this bundle (see https://github.com/overblog/GraphQLBundle/tree/master/lib/generator).

Of course I created a PR with a fix for the generator package (see https://github.com/overblog/GraphQLPhpGenerator/pull/29, pls merge ASAP) but for the future I think it would be best if this bundle installed the package normally via composer instead of embedding it like this. What is the reason for that anyway??

**Comment by mcg-web** [comment]
The generator repository become readonly, because It was difficult to maintain both at the same time since the generator was first created for the use of this bundle. I going to add a script to automatically update the generator repos from this one, I'm working on it this should be done today.

**Comment by mcg-web** [comment]
done created 2 new releases v0.11.17 extract from 0.11 branch and v0.12.5 from 0.12.

**Comment by enumag** [comment]
Thank you!

**Comment by enumag** [comment]
@mcg-web Can you pls change the default branch of https://github.com/overblog/GraphQLPhpGenerator repository to `master`?

**Comment by mcg-web** [comment]
Done!
