### ISSUE TITLE
Only allow introspection for logged in users

### ISSUE THREAD

**Issue by ruudk** [overblog/GraphQLBundle#629]
Is it possible to have [introspection disabled](https://github.com/overblog/GraphQLBundle/blob/master/docs/security/disable_introspection.md) by default and only for logged in users (with specific role)?

**Comment by mcg-web** [comment]
This not possible with the bundle but with Symfony with a dedicated environment by using a different host by example you could enable it only for this environment.

**Comment by ruudk** [comment]
That’s not really what I want. Do you think it’s possible to make this dynamic basis on a security listener ?

**Comment by mcg-web** [comment]
Yes this is possible since it is a service registration method that enable or disable introspection. [Here are the methods](https://github.com/overblog/GraphQLBundle/blob/05eb609523424e6d46914b67c795f107b93269c3/src/Request/Executor.php#L123-L131).

**Comment by ruudk** [comment]
It worked. Thanks a lot.
