### ISSUE TITLE
Upgrading from 0.12.5 to 0.13 fails with auto wire error on ExpressionFunction\Security\GetUser

### ISSUE THREAD

**Issue by ruudk** [overblog/GraphQLBundle#631]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? | yes
| RFC?             | no
| Version/Branch   | 0.13

```
Cannot autowire service "Overblog\GraphQLBundle\ExpressionLanguage\ExpressionFunction\Security\GetUser": argument "$security" of method "__construct()" references class "Symfony\Component\Security\Core
  \Security" but no such service exists
```

Not sure what I'm doing wrong.

**Comment by murtukov** [comment]
@ruudk try to install the Security Bundle
```
composer require symfony/security-bundle
```

**Comment by ruudk** [comment]
But I don't need Secure Bundle. Maybe the ExpressionLanguage should only register when you have that bundle enabled?

**Comment by ruudk** [comment]
In my project I only have `symfony/security-core`

**Comment by mcg-web** [comment]
This is definitely a bug, security should be optional. I started working on a fix I will submit a PR by tomorrow.

**Comment by ruudk** [comment]
Thanks, now that that is merged we can close this
