### ISSUE TITLE
Cannot declare class App\GraphQL\Resolver\[Resolver Name]because the name is already in use

### ISSUE THREAD

**Issue by brettins** [overblog/GraphQLBundle#632]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes/no
| Version/Branch   | 0.13.0

Hi! I've seen this issue on the forums a few times but the solutions don't seem to fit with my issue. 

```
PHP Fatal error:  Cannot declare class App\GraphQL\Resolver\TemplateInfo, because the name is already in use in /var/www/[appname]/src/GraphQL/TemplateInfo.php on line 8
PHP Stack trace:
PHP   1. {main}() /var/www/[appname]/bin/console:0
PHP   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /var/www/[appname]/bin/console:42
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /var/www/[appname]/vendor/symfony/console/Application.php:149
PHP   4. Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() /var/www/[appname]/vendor/symfony/framework-bundle/Console/Application.php:65
PHP   5. App\Kernel->boot() /var/www/[appname]/vendor/symfony/framework-bundle/Console/Application.php:159
PHP   6. App\Kernel->initializeContainer() /var/www/[appname]/vendor/symfony/http-kernel/Kernel.php:133
PHP   7. Symfony\Component\DependencyInjection\ContainerBuilder->compile() /var/www/[appname]/vendor/symfony/http-kernel/Kernel.php:556
PHP   8. Symfony\Component\DependencyInjection\Compiler\Compiler->compile() /var/www/[appname]/vendor/symfony/dependency-injection/ContainerBuilder.php:753
PHP   9. Symfony\Component\DependencyInjection\Compiler\ResolveInstanceofConditionalsPass->process() /var/www/[appname]/vendor/symfony/dependency-injection/Compiler/Compiler.php:94
PHP  10. Symfony\Component\DependencyInjection\Compiler\ResolveInstanceofConditionalsPass->processDefinition() /var/www/[appname]/vendor/symfony/dependency-injection/Compiler/ResolveInstanceofConditionalsPass.php:43
PHP  11. Symfony\Component\DependencyInjection\ContainerBuilder->getReflectionClass() /var/www/[appname]/vendor/symfony/dependency-injection/Compiler/ResolveInstanceofConditionalsPass.php:68
PHP  12. Symfony\Component\Config\Resource\ClassExistenceResource->isFresh() /var/www/[appname]/vendor/symfony/dependency-injection/ContainerBuilder.php:353
PHP  13. class_exists() /var/www/[appname]/vendor/symfony/config/Resource/ClassExistenceResource.php:78
PHP  14. spl_autoload_call() /var/www/[appname]/vendor/symfony/config/Resource/ClassExistenceResource.php:78
PHP  15. Symfony\Component\Debug\DebugClassLoader->loadClass() /var/www/[appname]/vendor/symfony/config/Resource/ClassExistenceResource.php:78
PHP  16. Composer\Autoload\ClassLoader->loadClass() /var/www/[appname]/vendor/symfony/debug/DebugClassLoader.php:163
PHP  17. Composer\Autoload\includeFile() /var/www/[appname]/vendor/composer/ClassLoader.php:322
PHP  18. include() /var/www/[appname]/vendor/composer/ClassLoader.php:444

In TemplateInfo.php line 8:
                                                                               
  Compile Error: Cannot declare class App\GraphQL\Resolver\TemplateInfo, beca  
  use the name is already in use                                               
                                                                               


```

I'm not using YAML, I'm depending on the mentioned [auto-discovery in the PHP method for resolvers](https://github.com/overblog/GraphQLBundle/blob/master/docs/definitions/resolver.md#the-php-way). The file is in `src/GraphQL/`. I'm wondering if this is a conflict with Symfony auto-wiring and the package's resolver, but I'm too new to Symfony to be able to tell.

**Comment by mcg-web** [comment]
Hi! can you provide some service configuration example please?

**Comment by calvera** [comment]
you probably have wrong namespace for class in the php file

**Comment by brettins** [comment]
> you probably have wrong namespace for class in the php file
```
<?php
# src/GraphQL/Resolver/Greetings.php
namespace App\GraphQL\Resolver;

use Overblog\GraphQLBundle\Definition\Resolver\ResolverInterface;

class Greetings implements ResolverInterface
{
    public function sayHello($name)
    {
        return sprintf('hello %s!!!', $name);
    }
}
```

namespace is what was recommended in the overblog docs

**Comment by brettins** [comment]
> Hi! can you provide some service configuration example please?

I'm super new to Symfony and all of this - can you tell me what files or content you'd like to see? I'm not sure what service configuration would refer to.

**Comment by murtukov** [comment]
@brettins Check if somewhere in your project you import or use a statement having the same name as the class your defining. e.g.:

```php
use FOS\UserBundle\Form\Type\RegistrationFormType;

class RegistrationFormType extends AbstractType
{
```

Here I import the class `RegistrationFormType` and then try to declare a class with the same name which of course leads to a conflict

**Comment by murtukov** [comment]
From your stack trace it states that it cannot declare this class:
`App\GraphQL\Resolver\TemplateInfo`
which is located here:
`/var/www/[appname]/src/GraphQL/TemplateInfo.php`

which is strange, because you dont have `Resolver` in the path. You messed something with namespaces for sure.

**Comment by brettins** [comment]
> Check if somewhere in your project you import or use a statement having the same name as the class your defining. e.g.:

Hi, unfortunately while that would certainly be the obvious fix, I had renamed it from `TemplateInfo` to `TemplateInfoz` and got the same error. (

> From your stack trace it states that it cannot declare this class:
> `App\GraphQL\Resolver\TemplateInfo`
> which is located here:
> `/var/www/[appname]/src/GraphQL/TemplateInfo.php`
> 
> which is strange, because you dont have `Resolver` in the path. You messed something with namespaces for sure. Please provide the code of the class `App\GraphQL\Resolver\TemplateInfo` and check if 2 of them exist.

Only one exists, the one I pasted [here](https://github.com/overblog/GraphQLBundle/issues/632#issuecomment-573156631) and the renaming to "TemplateInfoz" would have fixed that issue, and I'm not aware of an issue where the folder structure needs to match the namespace exactly. I also have tried moving TemplateInfo.php into src/GraphQL and still get the same error.

**Comment by murtukov** [comment]
@brettins Is it possible to upload the entire project to a repository, so that I could reproduce the issue?

**Comment by akomm** [comment]
@brettins 

- run `composer dump-autoload -o` and check if that resolves the issue - there are some edge-cases that leads to seemingly duplicated declarations.

Else:

- search for use & declaration of `TemplateInfo`, first only in your apps source code (exclude vendor/var, etc). example grep: `grep -rE "(^class TemplateInfo)|(use .*\\TemplateInfo;$)" project/src` and look for declaration duplicates, or import & declaration conflict as @murtukov stated

Else:

- Do the above, just move a directory up to also check in var/vendor, because cache files might also be the issue. In example above, the path would change from `project/src` to `project`.

**Comment by murtukov** [comment]
Closing this issue due to the lack of feedback.
