### ISSUE TITLE
Can we inject a service into args, fields ,field builder.

### ISSUE THREAD

**Issue by videni** [overblog/GraphQLBundle#634]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             |no
| Version/Branch   | 0.13

I have a grid bundle  which is used to define filter, column , sorter for a data table, these info can also be used to define Relay connection arguments and response type. that is we need to inject a service into args, fields ,field builder. something like following. currently the `BuilderProcessor` doen't use service from Symfony service container, so we have no way to use an existing service within our custom args builder.

```
class FilterInput  implements MappingInterface
{
    private $gridManager;

    public function __construct(Manager $gridManager)
    {

        $this->gridManager = $gridManager;
    }

    public function toMappingDefinition(array $config): array
    {
        $input = [
            'first' => [
                'type' => 'Int',
            ],
            'after' => [
                'type' => 'String',
            ],
            'last' => [
                'type' => 'Int',
            ],
            'before' => [
                'type' => 'String',
            ],
        ];

        if(!isset($config['grid'])) {
            throw new \LogicException('Grid is required for FilterInput');
        }
        $configuration = $this->gridManager->getConfigurationForGrid($config['grid']);
        //Add arguments  to $input based on $configuration got from gridManager, this service is available for build time and run time.

        return $input;
    }
```

**Comment by mcg-web** [comment]
This is not possible since builders are processed before container compilation.

**Comment by akomm** [comment]
@videni Do you intend to create new `graphql` types?

**Comment by murtukov** [comment]
Closing this issue due to lack of feedback.
