### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by Vincz** [overblog/GraphQLBundle#637]
| Q                | A
| ---------------- | -----
| Bug report?      | yes

The `ArgumentTransformer` needs the `symfony/property-access` component.  
We should update the composer.json accordingly or we get a Class Not found Exception.

**Comment by Vincz** [comment]
The `symfony/validator` is missing too.

**Comment by mcg-web** [comment]
This is normal, validator is optional

**Comment by Vincz** [comment]
Ok, so I made a PR to fix the ArgumentsTransformer.
View #642

**Comment by wiese** [comment]
> This is normal, validator is optional

https://getcomposer.org/doc/04-schema.md#suggest

**Comment by mcg-web** [comment]
Yes @wiese this is an acceptable fix, do you want to submit a PR for 0.13 branch?

**Comment by wiese** [comment]
@mcg-web I was about to but then realized [it is already mentioned in `require-dev`](https://github.com/overblog/GraphQLBundle/blob/28d74534f09e452bb3e236e690f3069166c71367/composer.json#L66)... Keep in mind I do not know how this code base does what it does and what (if any) is its "plan B" if  `symfony/validator` is not installed.
#642 seems to push to truly make it optional but [there is more to this](https://github.com/overblog/GraphQLBundle/blob/10942eeff219099b293719a7484f63a529e483a4/src/Transformer/ArgumentsTransformer.php#L37).
