### ISSUE TITLE
Code-generation entity to graphql file

### ISSUE THREAD

**Issue by god1dog** [overblog/GraphQLBundle#647]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | master

Since I have quite a few symfony projects, I often encounter the problem of code-generating entities into graphql files
Please add the command `php bin/console make:graphql-generate` 🙏

**Comment by mcg-web** [comment]
Do you have a look to [this bundle](https://github.com/Liinkiing/graphql-maker-bundle)?

**Comment by mcg-web** [comment]
Closing this issue due to the lack of feedback.
