### ISSUE TITLE
Include Altair GraphQL

### ISSUE THREAD

**Issue by imolorhe** [overblog/GraphQLBundle#653]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | n/a

I would love to be able to use [Altair GraphQL Client](https://altair.sirmuel.design/) as a view like the GraphiQL view, especially since it provides several extra features than the normal graphiql (like file uploading, setting headers, etc). Would it be possible to include a view for Altair?

**Comment by mcg-web** [comment]
Like GraphiQL this bundle does not have it out-of-the-box. If you think this could be useful you can create an external bundle adding this feature.
