### ISSUE TITLE
issue in file upload mutation

### ISSUE THREAD

**Issue by arshad111** [overblog/GraphQLBundle#662]
![Screenshot from 2020-03-09 16-24-18](https://user-images.githubusercontent.com/15728805/76216467-a5f0d000-6236-11ea-9086-5df8a087badf.png)
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no
| Version/Branch   | x.y.z

using : michaelperrin/blog-graphql-upload-demo

I have implemented GraphQL in my project and make mutation with file input as per : http://blog.michaelperrin.fr/2018/09/19/implementation-of-agraphql-mutation-with-file-upload/

but i have one question , how to call this in postman.

i am getting one issue
"debugMessage": "Notice: Undefined index: picture",
while uploading file as input
using : http://blog.michaelperrin.fr/2018/09/19/implementation-of-agraphql-mutation-with-file-upload/

Please help me i'm stuck in this critical issue and also find attachment.

**Comment by murtukov** [comment]
Hi @arshad111 .

What do you mean by "postman"? And what does it have to do with the issue? I see on the screenshot [Altair GraphQL Client](https://altair.sirmuel.design/). Your question is not clear, try to provide more details or, if possibble, you could upload your project to github and I would check it out.

**Comment by arshad111** [comment]
Hi @murtukov ,
My question is that i have an issue in while upload file using mutation and i have used : http://blog.michaelperrin.fr/2018/09/19/implementation-of-agraphql-mutation-with-file-upload/ 
but i got issue undefined index : picture.
Do you explaing what i miss or what is wring in above link.
Or can you please give me reference of file upload in graphql(small demo project and its steps)

**Comment by murtukov** [comment]
@arshad111 I will take a look at it later, don't have much time right now.

You can also contact me and other developers on official Slack and Telegram channels:
https://github.com/overblog/GraphQLBundle#community

**Comment by mcg-web** [comment]
hi @arshad111 , can you try to replace `args['input']` by `value` in your schema (yaml) definition please?

**Comment by arshad111** [comment]
@mcg-web  in both args or only in picture argument?

**Comment by murtukov** [comment]
@arshad111 Did you solve the issue? I still didn't find time to investigate it.

**Comment by arshad111** [comment]
yes @murtukov,this issue was solved :)
