### ISSUE TITLE
Whats the difference between UserWarning and UserError?

### ISSUE THREAD

**Issue by ktrzos** [overblog/GraphQLBundle#664]
Reference to [this](https://github.com/overblog/GraphQLBundle/blob/master/docs/error-handling/index.md) article.

I'm asking, because I see no difference in implementation of those classes. Is there a difference in usage or catching exceptions on front-end side?

Thank you in advance for making it more clear to me :).

**Comment by mcg-web** [comment]
`UserWaning` are display under the json response `extensions.warnings` section. `extensions` section are  not interpreted out-of-the box by front-end apps VS `UserError` that are display in interpreted in errors section in response.

**Comment by ktrzos** [comment]
Oh, ok :). Thanks!
