### ISSUE TITLE
Complex permissions in GraphQL

### ISSUE THREAD

**Issue by carlespibernat** [overblog/GraphQLBundle#666]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no?
| BC Break report? | no
| RFC?             | no
| Version/Branch   | master

I have a question that I don't know if can be solved with some bundle's feature or not. 
I have a problem related with permissions, and I think that it could be easily solved with some schema configuration (maybe it already exists something like that).

So, imagine a have a share files app such as Dropbox. In my app i can share files (which are objects of `File` entity) and files are into a directory (which is an object of `Directory` entity).

Imagine a directory with name "My directory" has two files: "z.txt" and "y.txt". Me as a user A want to share the "z.txt" file with a user B. So now user B is granted to view the "z.txt" file. Everything works nice so if user B makes this query:

```graphql
file (filename: "z.txt") {
  id
}
```

The app will properly return the "z.txt" file id. But if the same user makes the query:
```graphql
file (filename: "y.txt") {
  id
}
```

The API will return a permission error as the resolver is checking if user B has permission to view file "y.txt".

So everything is nice. The problem comes when user B makes this query:
```graphql
file (filename: "z.txt") {
  directory {
    files {
      id
    }
  }
}
```

The resolver is not denying the access as user B is allowed to view "z.txt" file, but the user can list all "z.txt" file directory files, so he is accessing to files that he is not allowed to view. 

I understand I could check in my resolver if the user is requesting for files in file parent directory but, If the application grows and begins to implement many relation between many objects then the implementation logic grows exponentially, and I don't think that its a good option. 

I've seen in the documentation that you can specify some permissions to see an object field with [Field access control](https://github.com/overblog/GraphQLBundle/blob/master/docs/security/fields-access-control.md) option, but I think (and maybe I'm wrong) that this doesn't solve the problem as user B must have permissions to view the directory but only list files where he is allowed to view. 

Maybe a good solution would be to add a configuration for a field that checks if user is granted to a specific field object. If its not then the object is removed from the response.

**Comment by murtukov** [comment]
@carlespibernat 

Essentially your question is "How to filter collection results by the authenticated user", because you already know, how to restrict acceess to the entire fields.

Your field `directory` can be accessed only by authenticated users, which means you should use the `access` option on it to prevent access by non authenticated users.

So if directory can only be accessed by authorized users, then you can always know, which user is requesting the directory and therefore you can filter the results inside the resolver.

```yaml
Query:
    type: object
    config:
        fields:
            directory:
                access: "@=isAuthenticated()"
                resolver: "@=resolve('getDirectory', [getUser()])"
                
                # ...
```

```php
public function getDirectory(UserInterface $user): iterable
{
    $filteredDirectories = $repository->getDirectoriesByUser($user);
    return $filteredDirectories;
}
```

**Comment by carlespibernat** [comment]
Yes, I understand that I can heck permissions in directory resolver, but my problem comes when there are many relations in the app, and almost all resolvers have to check many different permissions.
For example, the example I gave in the previous comment, if I try to get the directory files from the following query:
```graphql
file (filename: "z.txt") {
  directory {
    files {
      id
    }
  }
}
```

I'm creating a `file` query and then I go to its parent directory and then to the directory files. To check permissions here I should be checking into the `file` resolver if the client is asking for `directory/files` path.

But now imagine that files can have also comments. Then a client could be asking for the following query:
```graphql
comment (id: 5) {
  file {
    directory {
      files {
        id
      }
    }
  }
}
```
So now I should be checking a similar logic into the `comment` resolver

Even a client could do:
```graphql
directory {
  files {
    directory {
      files {
        id
      }
    }
  }
}
```
And now the `directory` resolver should check if the client is asking for the `directory/files/directory/files`...
So the possibilities are almost infinite, thats why I think that maybe it could be a good idea to create something like a filter before generating the response.

**Comment by gregoryalary** [comment]
Hello @carlespibernat, have you found a clean way to achieve this ?

**Comment by carlespibernat** [comment]
At the end I'm using https://github.com/webonyx/graphql-php instead of the bundle so I have more flexibility
