### ISSUE TITLE
Webonyx GraphQL v0.14

### ISSUE THREAD

**Issue by enumag** [overblog/GraphQLBundle#690]
vladar released the [v0.14](https://github.com/webonyx/graphql-php/releases/tag/v14.0.0) version recently. Of course this bundle doesn't support it yet.

Personally I'm no longer using the bundle. However I'm still using the [overblog/GraphQLPhpGenerator](https://github.com/overblog/GraphQLPhpGenerator) package. Is there some way to update it separately so that I don't have to wait for full bundle integration?

**Comment by mcg-web** [comment]
I'll make the requirements lease strict on the generator so this will not be a problem in the future.

**Comment by enumag** [comment]
Thanks!

**Comment by enumag** [comment]
ping @mcg-web

**Comment by mcg-web** [comment]
done @enumag . Since the lib is not more embedded in this bundle you can submit PR or issue directly in it repository.

**Comment by enumag** [comment]
Thanks for clarifying that. I was confused since the repo was marked as "readonly" until now.

Can you make a new release of the package?

**Comment by mcg-web** [comment]
done [overblog/GraphQLPhpGenerator v0.12.6](https://github.com/overblog/GraphQLPhpGenerator/releases/tag/v0.12.6)
