### ISSUE TITLE
Multi bundle graphql types

### ISSUE THREAD

**Issue by VincentClair** [overblog/GraphQLBundle#71]
Hello,

I have two bundles that are standalone (for example UserBundle and ProductBundle).
Each one define their own graphql Query types.

When I want to use those two bundle in the main application, i get a conflict on the Query.types.yml, as it is defined twice.

Do you have an advice to resolve this conflict ?
Do I need to define only one Query type in main app ? What about functional tests in this case in bundles ?

**Comment by mcg-web** [comment]
Hi,

Types name should be unique but [multiple schema](https://github.com/overblog/GraphQLBundle#multiple-schema-endpoint) can now be implemented

**Comment by VincentClair** [comment]
With this method, we lost the interest with only one entry point. No ?
It could be a problem to plug relay after that ?

Maybe the only solution is to rename Query types in each bundle to UserQuery and ProductQuery, then declare a new Query in main app, that fetch all define queries in the two previous one (to avoid an added level) ?

**Comment by mcg-web** [comment]
I agree with you, not because the bundle allow multiples schema you must use it. The unique name is a graphQL constraint. Rename type is the solution to keep single endpoint. We removed the types definitions merging to keep schema readable, we could think of a config to allow it...

**Comment by mcg-web** [comment]
Feel free to reopen if needed :)
