### ISSUE TITLE
Default schema consideration

### ISSUE THREAD

**Issue by Vincz** [overblog/GraphQLBundle#712]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe

I realised that I've always assumed that the default schema name is "default". But is it a correct assumption ?
If we have multiple schemas like this:

```
schemas:
   schema1:
       ...
   schema2:
       ...
```

Should we consider that there is no default schema or should we consider that the default schema is the first schema defined, ie `schema1`.

What about in this case:
```
schemas:
   schema1:
       ...
   schema2:
       ...
   default:
        ...
```

ping @mcg-web @murtukov

**Comment by murtukov** [comment]
@Vincz why do you need to determine which schema is default?

**Comment by Vincz** [comment]
I needed it in the annotations to get the default types `@Query` and `@Mutation` should apply when no `targetType` is defined (and I take the one with the name `default`).
It also used in the `Executor` to get the schema being executed if none is specified (it takes the first one defined).
And it's also used in the Data collector where it also consider the name 'default' if no schema is set.

**Comment by murtukov** [comment]
@Vincz I would use the first one, if no schema with `default` is defined explicitly
