### ISSUE TITLE
symfony 5.1 deprecation

### ISSUE THREAD

**Issue by hjanuschka** [overblog/GraphQLBundle#714]
since upgrading to sf5.1 i get the following deprecation.

graphqlbundle:   0.13.3
<img width="1877" alt="Bildschirmfoto 2020-07-14 um 14 22 43" src="https://user-images.githubusercontent.com/2891702/87425283-a8e14000-c5dd-11ea-81c7-3f9588a56eac.png">

**Comment by murtukov** [comment]
@hjanuschka fixed. Will be available in release 0.13.4

**Comment by hjanuschka** [comment]
thx!
