### ISSUE TITLE
CORS block

### ISSUE THREAD

**Issue by Emroni** [overblog/GraphQLBundle#717]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.13.3

After upgrading from `0.13.2` to `0.13.3` all requests are blocked by CORS. Downgrading back to `0.13.2` fixes it, so it seems to be a change in `0.13.3`.

Im using NelmioCorsBundle and found out that changing the `allow_origin` in config allows one request to succeed, but will block all requests after. Changing that value back to what is was, again allows one request and blocks the next.  
As it seemed to be a cache thing, deleting the cache folder (not just clearing it) fixed it, but again will only allow that first request and block the next.

**Comment by murtukov** [comment]
Hi @Emroni can you provide steps to reproduce it?

**Comment by Emroni** [comment]
I'm investigating if its my configuration. I had upgraded from PHP 7.1 to 7.4 and Symfony from 4.1 to 4.4 and think it might have something to do with that. Going to try out a fresh install and config, will see if it still happens then.

**Comment by Emroni** [comment]
It turned out to be an nginx `Bad Gateway` error that was thrown, causing the access-control headers not to be set, showing a CORS error in the browser without showing the Bad Gateway for some reason.

Not sure why clearing cache and switching variables made it work temporarily, but blaming nginx for this one :)
