### ISSUE TITLE
Default export path of graphql:dump-schema is incorrect

### ISSUE THREAD

**Issue by bartv2** [overblog/GraphQLBundle#733]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes/no
| RFC?             | yes/no
| Version/Branch   | master

The resulting path is var/var/schema.json, this directory does not exist by default. Not sure what the best approach is, changing the baseExportPath or removing the var directory component.

**Comment by mcg-web** [comment]
This is a bug the default dir should be `var/` not `var/var/`

**Comment by mcg-web** [comment]
fixed in #747
