### ISSUE TITLE
Resolve input-object to PHP object

### ISSUE THREAD

**Issue by PartosK** [overblog/GraphQLBundle#767]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.12.7

there was a question in comment:
https://github.com/overblog/GraphQLBundle/issues/479
for me this is also relevant, we do not use annotations. I would like some detailed example of how to do this.

**Comment by murtukov** [comment]
Duplicate #479 

Ask your questions directly in the #479.
