### ISSUE TITLE
Annotations, args builder for relay connection bug?

### ISSUE THREAD

**Issue by calvera** [overblog/GraphQLBundle#787]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.12.4

hi, should this work?
```php
/**
 * @GQL\Query(type="OrganisationConnection", argsBuilder="Relay::Connection")
 */
public function organisations(?string $after): ConnectionInterface
{
    dump($after);
}
```
i get this error:
{"errors":[{"debugMessage":"Too few arguments to function App\\GraphQL\\Query\\OrganisationProvider::organisations(), 0 passed in \/app\/var\/cache\/dev\/overblog\/graphql-bundle\/__definitions__\/RootQueryType.php on line 87 and exactly 1 expected","

**Comment by Vincz** [comment]
Hi Calvera. Sorry for the late reply.
It will not work. The Arguments transformer can only inject arguments in the resolver when it knows them before generating the resolver function of the query. It means that they must be declared with annotations or auto-guessed. 
Unfortunately, when using the the args builder, the arguments are generated after the annotations parsing.
You have two choice:
1. Remove the `argsBuilder` and let the auto-guessing generate the `after` args from your parameter.
2. Use the `argsBuilder` but add a `resolve` on your `@Query` to let the parser know how to call your resolver function. 

We are planning to rework the resolver arguments/parameters injection.

**Comment by calvera** [comment]
thanks!
