### ISSUE TITLE
OperationName is not passed to Events when using Batch query

### ISSUE THREAD

**Issue by edhgoose** [overblog/GraphQLBundle#789]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.13 and below

We provide an operationName for most if not all of our queries, and recently added an event listener to look at what operations were being executed.

When we use the batch endpoint, the line here does not pass the operationName through:
https://github.com/overblog/GraphQLBundle/blob/2b954fd7adc206a97b1fc013c5209e1cbc8bbebc/src/Controller/GraphController.php#L101

As such, the operationName is always null.

I've manually modified our code and find passing the operationName here works fine.

**Comment by mcg-web** [comment]
Thanks for the fix @edhgoose ! Can you please provide the patch for 0.11 branch please ? Then we can apply it to versions above.
