### ISSUE TITLE
Nested arguments are not passed down to child elements

### ISSUE THREAD

**Issue by corleonis** [overblog/GraphQLBundle#8]
I have following example:

```
{
  company(id: "123") {
    name, 
    directors(active: true) {
        name
    }
}
```

so problem is once we call the nested `directors` in the resolver we pass just the `[value]` which is the company data but the arguments are skipped. This is a valid GraphQL query though.

**Comment by mcg-web** [comment]
If you using the resolver expresion function you must explicitly inject the args like this: `@=resolver('my_resolver', [value, args])` . You can see https://github.com/overblog/GraphQLBundle#expression-language for more details...

**Comment by corleonis** [comment]
thanks, I fuggured it out :)
