### ISSUE TITLE
Missing symfony/validator dependency in composer.json

### ISSUE THREAD

**Issue by olsavmic** [overblog/GraphQLBundle#842]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.13.6

The symfony/validator component is required only in dev dependencies.

In https://github.com/overblog/GraphQLBundle/issues/637#issue-552371174, it is said that the symfony/validator component is optional but that is unfortunately not true.

`\Overblog\GraphQLBundle\Transformer\ArgumentsTransformer::getInstanceAndValidate (line 155)` function creates an instance of `Symfony\Component\Validator\ConstraintViolationList` even when no validator is configured.

I think that either proper test case must be added checking if the validator really can be optional or it should be added as a required dependency.

**Comment by Vincz** [comment]
Hi @olsavmic,
I don't understand, the Constraints list is created after this line:
https://github.com/overblog/GraphQLBundle/blob/40b7eac69d9dacc897a69dc23eb9a4e144fac8e9/src/Transformer/ArgumentsTransformer.php#L143

So, it is not created if there is no validator. 
Which version are you working with?

**Comment by murtukov** [comment]
@olsavmic then the issue can be closed I guess

**Comment by olsavmic** [comment]
@murtukov  

Yes it's in the master branch but is there any reason why the fix was not merged to a release branch a year later? 
We can close the issue once this is resolved.

**Comment by olsavmic** [comment]
@Vincz ping (Fix is already in the master branch fro months as you found out, it just has to be released)

**Comment by olsavmic** [comment]
@mcg-web @Vincz @murtukov This issue is still open and keeps the release possibly broken even though the fix is in the master. Can we please resolve it?

**Comment by olsavmic** [comment]
It's finally released in 0.14, thank you! (although it's missing from the release notes). Closing this issue.
