### ISSUE TITLE
Cache directories

### ISSUE THREAD

**Issue by murtukov** [overblog/GraphQLBundle#844]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Feature request? | no
| BC Break report? | no
| Version/Branch   | 0.14

I've noticed some strange codes, when it comes to `cacheDir`/`baseCacheDir` in the `TypeGenerator`.

Check out the method `getCacheDir`:
```php
public function getCacheDir(bool $useDefault = true): ?string
{
    if ($useDefault) {
        return $this->cacheDir ?: $this->baseCacheDir.'/overblog/graphql-bundle/__definitions__';
    } else {
        return $this->cacheDir;
    }
}
```
The `$useDefault` parameter doesn't affect anything: 

- If it's `true`, then the method returns `$this->cacheDir`
- If it's `false`, then it also returns `$this->cacheDir`

So the method can be simplified to this:
```php
public function getCacheDir(): ?string
{
    return $this->cacheDir ?? $this->baseCacheDir.'/overblog/graphql-bundle/__definitions__';
}
```

But then I checked where this method is used. It is called only in one place: `Overblog\GraphQLBundle\CacheWarmer\CompileCacheWarmer::warmUp`

```php
public function warmUp($cacheDir)
{
    if ($this->compiled) {
        // use warm up cache dir if type generator cache dir not already explicitly declare
        $baseCacheDir = $this->typeGenerator->getBaseCacheDir();
        if (null === $this->typeGenerator->getCacheDir(false)) {
            $this->typeGenerator->setBaseCacheDir($cacheDir);
        }
        $this->typeGenerator->compile(TypeGenerator::MODE_WRITE | TypeGenerator::MODE_OVERRIDE);

        if (null !== $baseCacheDir) {
            $this->typeGenerator->setBaseCacheDir($baseCacheDir);
        }
    }

    return [];
}
```

@mcg-web please review these methods and check if the `cacheDir` and `baseCacheDir` are used correctly.

**Comment by mcg-web** [comment]
`cacheDir` is null by default.  We use `null` to determine that the developer has not change the `cacheDir` option to a custom value. 
So the `$useDefault` parameter can affect the output of the method if `$cacheDir` is null:

```php
    //$this->cacheDir = null;
    if ($useDefault) {
        return $this->cacheDir ?: $this->baseCacheDir.'/overblog/graphql-bundle/__definitions__'; // return $this->baseCacheDir.'/overblog/graphql-bundle/__definitions__' if $useDefault is true
    } else {
        return $this->cacheDir; // return null if $useDefault is false
    }
```
`$useDefault` mean that we does not get the rawValue of `$cacheDir` but we send a default value if it value is null. `$useDefaut = !$rawValue` 

This was introduce in 0.10 #337 to fix the type generator with Symfony warmup issue #301.
