### ISSUE TITLE
Update dependencies crash GraphQL

### ISSUE THREAD

**Issue by Ciloe** [overblog/GraphQLBundle#859]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Version/Branch   | dev-master#f32d17c41db369469d3d5b69030e386db882356e
| Webonyx   | dev-master#5bc702b6f24369402d91cdaf61fdf253438fbf49

This is the error : 

[▼
"exception" => Error {#1188 ▼
#message: "Typed property GraphQL\Validator\Rules\ValidationRule::$name must not be accessed before initialization"
#code: 0
#file: "/Users/jimmy/Development/project/symfony/vendor/webonyx/graphql-php/src/Validator/Rules/ValidationRule.php"
#line: 20
trace: {▶}
}
]
{▼
/Users/jimmy/Development/project/symfony/vendor/webonyx/graphql-php/src/Validator/Rules/ValidationRule.php:20 {▶}
/Users/jimmy/Development/project/symfony/vendor/webonyx/graphql-php/src/Validator/DocumentValidator.php:263 {▶}
/Users/jimmy/Development/project/symfony/vendor/overblog/graphql-bundle/src/Request/Executor.php:123 {▶}
/Users/jimmy/Development/project/symfony/var/cache/dev/ContainerXI8x2Zy/getOverblogGraphql_RequestExecutorService.php:33 {▶}
/Users/jimmy/Development/project/symfony/var/cache/dev/ContainerXI8x2Zy/App_KernelDevDebugContainer.php:683 {▶}
/Users/jimmy/Development/project/symfony/var/cache/dev/ContainerXI8x2Zy/getGraphControllerService.php:26 {▶}
/Users/jimmy/Development/project/symfony/var/cache/dev/ContainerXI8x2Zy/App_KernelDevDebugContainer.php:683 {▶}
/Users/jimmy/Development/project/symfony/vendor/symfony/dependency-injection/Container.php:246 {▶}
/Users/jimmy/Development/project/symfony/vendor/symfony/dependency-injection/Container.php:228 {▶}
/Users/jimmy/Development/project/symfony/vendor/symfony/http-kernel/Controller/ContainerControllerResolver.php:53 {▶}
/Users/jimmy/Development/project/symfony/vendor/symfony/framework-bundle/Controller/ControllerResolver.php:29 {▶}
/Users/jimmy/Development/project/symfony/vendor/symfony/http-kernel/Controller/ControllerResolver.php:120 {▶}
/Users/jimmy/Development/project/symfony/vendor/symfony/http-kernel/Controller/ContainerControllerResolver.php:42 {▶}
/Users/jimmy/Development/project/symfony/vendor/symfony/http-kernel/Controller/ControllerResolver.php:86 {▶}
/Users/jimmy/Development/project/symfony/vendor/symfony/http-kernel/Controller/TraceableControllerResolver.php:38 {▶}
/Users/jimmy/Development/project/symfony/vendor/symfony/http-kernel/HttpKernel.php:140 {▶}
/Users/jimmy/Development/project/symfony/vendor/symfony/http-kernel/HttpKernel.php:79 {▶}
/Users/jimmy/Development/project/symfony/vendor/symfony/http-kernel/Kernel.php:199 {▶}
/Users/jimmy/Development/project/symfony/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:37 {▶}
/Users/jimmy/Development/project/symfony/vendor/autoload_runtime.php:35 {▶}
/Users/jimmy/Development/project/symfony/public/index.php:5 {▶}
}

**Comment by mcg-web** [comment]
@Ciloe are you still having this issue with last master version ?

**Comment by Ciloe** [comment]
I will test that ASAP !

**Comment by Ciloe** [comment]
Nice, it's working ❤️
