### ISSUE TITLE
What's the status of 0.14 (DEV)? Can it be tagged?

### ISSUE THREAD

**Issue by ruudk** [overblog/GraphQLBundle#887]
Is 0.14 still in development? If so, where can I find what's blocking a release? There is no [milestone](https://github.com/overblog/GraphQLBundle/milestones) for it.

I really want to upgrade to `webonyx/graphql-php` v14.

**Comment by davidPaymefy** [comment]
any update on when this is scheduled to happen?

**Comment by mcg-web** [comment]
0.14 will be release this week @davidPaymefy .

**Comment by ruudk** [comment]
https://github.com/overblog/GraphQLBundle/releases/tag/v0.14.0
