### ISSUE TITLE
Uncaught Error: Class "Overblog\GraphQLBundle\DependencyInjection\Compiler\ResolverTaggedServiceMappingPass" not found

### ISSUE THREAD

**Issue by benelori** [overblog/GraphQLBundle#896]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Version/Branch   | dev-master

As the title suggests, the bundle file is missing that compiler pass.

I traced it down to the PR that removed the deprecated code, and I also saw that the scrutinizer reports showed this, but the pipeline did not fail.
https://github.com/overblog/GraphQLBundle/pull/893/checks?check_run_id=3894977836

**Comment by mcg-web** [comment]
fixed from 0.14
