### ISSUE TITLE
[1.0-dev] `TypeGeneratorPass` should not retrieve `TypeGenerator` service from container while the container is compiling

### ISSUE THREAD

**Issue by ruudk** [overblog/GraphQLBundle#899]
I noticed something weird when upgrading from 0.13 to 0.14 or 1.0-dev. 

I have this service definition in my config:
```php
$services->set(\League\StatsD\Client::class)
        ->call(
            'configure',
            [
                [
                    'throwConnectionExceptions' => false,
                    'host' => '%env(string:STATSD_HOST)%',
                    'port' => '%env(int:STATSD_PORT)%',
                ],
            ]
        );
```

It would work properly on 0.13. But as soon as I switch to 0.14/1.0-dev I get the following error:
```
In Client.php line 138:                   
Port is out of range 
````

I traced this down and saw that `TypeGeneratorPass` is instantiating the container while it's being compiled/build. It prevents the resolving of env vars to work properly. Therefore the Client retrieves `%env(int:STATSD_PORT)%` as the port, while it expects a number.

This issue is similar to https://github.com/overblog/GraphQLBundle/issues/588.

There, somebody already mentions that you should not use services in compiler passes.
> As a rule, only work with services definition in a compiler pass and do not create service instances. In practice, this means using the methods has(), findDefinition(), getDefinition(), setDefinition(), etc. instead of get(), set(), etc.

https://symfony.com/doc/current/components/dependency_injection/compilation.html#execute-code-during-compilation

Is the `TypeGeneratorPass` really needed?

**Comment by ruudk** [comment]
I think it's because `master` is linked to https://webonyx.github.io/graphql-php dev-master. When they release a new major, master can also be tagged.

But I'm no longer using this bundle. Instead, I directly work with webonyx now.

**Comment by mcg-web** [comment]
@loru88 0.15 came from 0.14 not 1.0-dev (master branch) , anyway the change was include in the last release v0.15.1.
