### ISSUE TITLE
Is there any tool to transform a graphql schema to a yml schema ?

### ISSUE THREAD

**Issue by gregoryalary** [overblog/GraphQLBundle#900]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.13

Hello, 👋 

Firstly, thanks for all the work you're putting in this package, this is awesome. 

I'm working on a project which uses your package and that's based on a massive GraphQL schema written in "GraphQL language". Though, I would like to work with the `public` attribute of the yaml definition to restrict the access on some data. 
Since the schema is written in "GraphQL" language, I can't use this `public` attribute to write the access logic in the schema so I have to translate it into yml, which is a MASSIVE work.
So I'm wondering if there's any tool to automate this process ?

Thanks in advance.

**Comment by murtukov** [comment]
@gregoryalary AFAIK there is no such tool. Consider using PHP classes to define your types: https://github.com/overblog/GraphQLBundle/discussions/889

**Comment by gregoryalary** [comment]
Thanks for you anwser ! Is there any downside from using YAML instead of PHP classes ?

**Comment by murtukov** [comment]
@gregoryalary they aren't opposite things, therefore not comparable. YAML configs are used to generate these PHP classes which are then actually used to define your GraphQL schema. So when you are deciding towards PHP classes you are just skipping an extra step. There is nothing unique in YAML configs what you can't do in PHP classes.
