### ISSUE TITLE
Add support for isDeprecated / deprecatedReason

### ISSUE THREAD

**Issue by ruudk** [overblog/GraphQLBundle#92]
Seems like it's not allowed to define it in the field config.

**Comment by mcg-web** [comment]
Thanks for bringing this up!

**Comment by mcg-web** [comment]
[Webonyx/GraphQL-PHP](https://github.com/webonyx/graphql-php) is not supporting the `isDeprecated` config entry right now but `deprecationReason` work properly. I add tips on documentation to deprecate object fields and enum value using `deprecationReason`...

**Comment by mcg-web** [comment]
I'll keep this open while waiting for `isDeprecated` in webonyx/graphql-php.

**Comment by mcg-web** [comment]
Closing this, feel free to re open if needed :+1:

**Comment by vladar** [comment]
FYI, `isDeprecated` is inferred from `deprecationReason` and is already exposed in Introspection results in graphql-php. 

But it will not be added as separate config entry. It is done the same way as in reference implementation on purpose: to enforce best practices of documenting why some field was actually deprecated.

So in terms of type definitions `deprecationReason` is all you need.
