### ISSUE TITLE
Pass requested fields to resolver

### ISSUE THREAD

**Issue by ruudk** [overblog/GraphQLBundle#98]
| Q                | A
| ---------------- | -----
| Bug report?      |no
| Feature request? |no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | master

Is it possible to get the requested fields inside the resolver? I have a field that takes a heavy calculation and I only want to execute that calculation when the user actually queries for it. 

For example:
```
query {
  event(id: "1") {
    id
    totalNumberOfUsers
  }
}
```

The calculation of `totalNumberOfUsers` is heavy and I only want to execute that when the user is actually querying for that information. 

Any ideas?

I checked all possible values I could pass to my resolver:
```
@=resolver('event', [args, value, info, context])
```

But none contain the information needed.

**Comment by ruudk** [comment]
I already solved it by returning the value as a closure. Easy :D

**Comment by mcg-web** [comment]
Because this can help, you can also use `info.getFieldSelection()` to get the fields user selected...

**Comment by ruudk** [comment]
Ahh, so I was close with the `info` one. Thanks!
