### ISSUE TITLE
Add support of native php8.1 enums

### ISSUE THREAD

**Issue by Makapashev** [overblog/GraphQLBundle#990]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Version/Branch   | 0.14.2

**Comment by systemasis** [comment]
This issue has been resolved on `master` for a month now. Is there anything delaying the release of a stable version including this fix ?

I would love to move to native enumerations without temporary workarounds in my projects.

**Comment by eteos** [comment]
[v15 of webonyx/graphql-bundle](https://github.com/webonyx/graphql-php/releases/tag/v15.0.0) has been released

**Comment by Vincz** [comment]
The [v1.0](https://github.com/overblog/GraphQLBundle/releases/tag/v1.0.0) has been released with enum support.
